-- ----------------------------------------------------------------------------------------
-- EDATOS-3047 - Realizar la carga de datos en background
-- ----------------------------------------------------------------------------------------

CREATE TABLE TB_TASKS (
  ID NUMBER(19) NOT NULL,
  JOB VARCHAR2(4000 CHAR) NOT NULL,
  EXTENSION_POINT VARCHAR2(4000 CHAR),
  CREATED_DATE_TZ VARCHAR2(50 CHAR),
  CREATED_DATE TIMESTAMP,
  CREATED_BY VARCHAR2(50 CHAR),
  LAST_UPDATED_TZ VARCHAR2(50 CHAR),
  LAST_UPDATED TIMESTAMP,
  LAST_UPDATED_BY VARCHAR2(50 CHAR),
  VERSION NUMBER(19) NOT NULL,
  STATUS VARCHAR2(255 CHAR) NOT NULL
);

ALTER TABLE TB_TASKS ADD CONSTRAINT PK_TB_TASKS
	PRIMARY KEY (ID)
;

ALTER TABLE TB_TASKS
	ADD CONSTRAINT UQ_TB_TASKS UNIQUE (JOB)
;

CREATE SEQUENCE SEQ_TASKS;