-- --------------------------------------------------------------------------------------------------
-- EDATOS-5840 No se puede incrementar a version 3.7.0 de edatos-repository ya que no es compatible
--
-- Crea las tablas, secuencias y funciones de clonado necesarias para que Hibernate no falle
-- al hacer cascade-delete sobre DatasetEntity (nueva coleccion granularityAttributesInstances
-- en edatos-dataset-repository 3.7.0).
-- Las tablas estaran vacias en indicators pero deben existir para satisfacer las queries JPA.
-- --------------------------------------------------------------------------------------------------

-- Sequences
CREATE SEQUENCE SEQ_GRANULARITY_ATTRIBUTES;
CREATE SEQUENCE SEQ_GRANULARITY_ATTRIBUTE_DIMENSIONS;

-- Tables
CREATE TABLE TB_GRANULARITY_ATTRIBUTES (
    ID              BIGINT NOT NULL,
    ATTRIBUTE_ID    VARCHAR(100) NOT NULL,
    UUID            VARCHAR(36) NOT NULL,
    VERSION         BIGINT NOT NULL,
    VALUE_FK        BIGINT NOT NULL,
    DATASET_FK      BIGINT NOT NULL
);

ALTER TABLE TB_GRANULARITY_ATTRIBUTES ADD CONSTRAINT PK_TB_GRANULARITY_ATTRIBUTES
    PRIMARY KEY (ID);

ALTER TABLE TB_GRANULARITY_ATTRIBUTES
    ADD CONSTRAINT UQ_TB_GRANULARITY_ATTRIBUTES UNIQUE (UUID);

ALTER TABLE TB_GRANULARITY_ATTRIBUTES ADD CONSTRAINT FK_TB_GRANULARITY_ATTRIBUTES_VALUE_FK
    FOREIGN KEY (VALUE_FK) REFERENCES TB_INTERNATIONAL_STRINGS (ID);

ALTER TABLE TB_GRANULARITY_ATTRIBUTES ADD CONSTRAINT FK_TB_GRANULARITY_ATTRIBUTES_DATASET_FK
    FOREIGN KEY (DATASET_FK) REFERENCES TB_DATASETS (ID) ON DELETE CASCADE;


CREATE TABLE TB_GRANULARITY_ATTRIBUTE_DIMENSIONS (
    ID                          BIGINT NOT NULL,
    DIMENSION_ID                VARCHAR(100) NOT NULL,
    CODE_DIMENSION_ID           VARCHAR(100),
    GRANULARITY_CODE            VARCHAR(100),
    UUID                        VARCHAR(36) NOT NULL,
    VERSION                     BIGINT NOT NULL,
    GRANULARITY_ATTRIBUTE_FK    BIGINT NOT NULL
);

ALTER TABLE TB_GRANULARITY_ATTRIBUTE_DIMENSIONS ADD CONSTRAINT PK_TB_GRANULARITY_ATTRIBUTE_DIMENSIONS
    PRIMARY KEY (ID);

ALTER TABLE TB_GRANULARITY_ATTRIBUTE_DIMENSIONS
    ADD CONSTRAINT UQ_TB_GRANULARITY_ATTRIBUTE_DIMENSIONS UNIQUE (UUID);

ALTER TABLE TB_GRANULARITY_ATTRIBUTE_DIMENSIONS ADD CONSTRAINT FK_TB_GRANULARITY_ATTRIBUTE_DIMENSIONS_GRANULARITY_ATTRIBUTE_FK
    FOREIGN KEY (GRANULARITY_ATTRIBUTE_FK) REFERENCES TB_GRANULARITY_ATTRIBUTES (ID) ON DELETE CASCADE;

-- Clone functions
CREATE OR REPLACE FUNCTION CLONE_TB_GRANULARITY_ATTRIBUTE_DIMENSIONS(P_OLD_GRANULARITY_ATTRIBUTE_ID numeric,
                                                                      P_NEW_GRANULARITY_ATTRIBUTE_ID numeric)
RETURNS void AS
$$
DECLARE
    VA_COUNTER   numeric;
BEGIN
    SELECT COUNT(1)
    INTO VA_COUNTER
    FROM TB_GRANULARITY_ATTRIBUTE_DIMENSIONS
    WHERE GRANULARITY_ATTRIBUTE_FK = P_OLD_GRANULARITY_ATTRIBUTE_ID;

    IF VA_COUNTER > 0
    THEN
        INSERT INTO TB_GRANULARITY_ATTRIBUTE_DIMENSIONS
            (ID, DIMENSION_ID, CODE_DIMENSION_ID, GRANULARITY_CODE, UUID, VERSION, GRANULARITY_ATTRIBUTE_FK)
            (SELECT nextval('SEQ_GRANULARITY_ATTRIBUTE_DIMENSIONS') AS ID,
                    DIMENSION_ID AS DIMENSION_ID,
                    CODE_DIMENSION_ID AS CODE_DIMENSION_ID,
                    GRANULARITY_CODE AS GRANULARITY_CODE,
                    RANDOM_STRING(36) AS UUID,
                    VERSION AS VERSION,
                    P_NEW_GRANULARITY_ATTRIBUTE_ID AS GRANULARITY_ATTRIBUTE_FK
            FROM TB_GRANULARITY_ATTRIBUTE_DIMENSIONS
            WHERE GRANULARITY_ATTRIBUTE_FK = P_OLD_GRANULARITY_ATTRIBUTE_ID);
    END IF;
END;
$$ LANGUAGE plpgsql;


CREATE OR REPLACE FUNCTION CLONE_TB_GRANULARITY_ATTRIBUTES(P_OLD_DATASET_ID numeric,
                                                           P_NEW_DATASET_ID numeric)
RETURNS void AS
$$
DECLARE
    VA_SEQ                        numeric;
    VA_INTERNATIONAL_STRINGS_ID   numeric;

    CURSOR_TB_GRANULARITY_ATTRIBUTES CURSOR FOR
        SELECT *
        FROM TB_GRANULARITY_ATTRIBUTES
        WHERE DATASET_FK = P_OLD_DATASET_ID;

    ROW_TB_GRANULARITY_ATTRIBUTES RECORD;
BEGIN

    OPEN CURSOR_TB_GRANULARITY_ATTRIBUTES;
    LOOP
        FETCH CURSOR_TB_GRANULARITY_ATTRIBUTES INTO ROW_TB_GRANULARITY_ATTRIBUTES;
        EXIT WHEN NOT FOUND;

        SELECT nextval('SEQ_GRANULARITY_ATTRIBUTES') INTO VA_SEQ;

        VA_INTERNATIONAL_STRINGS_ID := CLONE_TB_INTERNACIONAL_STRINGS(ROW_TB_GRANULARITY_ATTRIBUTES.VALUE_FK);
        PERFORM CLONE_TB_LOCALISED_STRINGS(ROW_TB_GRANULARITY_ATTRIBUTES.VALUE_FK, VA_INTERNATIONAL_STRINGS_ID);

        INSERT INTO TB_GRANULARITY_ATTRIBUTES
            (ID, ATTRIBUTE_ID, UUID, VERSION, VALUE_FK, DATASET_FK)
            VALUES (VA_SEQ,
                    ROW_TB_GRANULARITY_ATTRIBUTES.ATTRIBUTE_ID,
                    RANDOM_STRING(36),
                    ROW_TB_GRANULARITY_ATTRIBUTES.VERSION,
                    VA_INTERNATIONAL_STRINGS_ID,
                    P_NEW_DATASET_ID);

        PERFORM CLONE_TB_GRANULARITY_ATTRIBUTE_DIMENSIONS(ROW_TB_GRANULARITY_ATTRIBUTES.ID, VA_SEQ);
    END LOOP;
    CLOSE CURSOR_TB_GRANULARITY_ATTRIBUTES;
END;
$$ LANGUAGE plpgsql;

-- Update CREATE_VERSION to also clone granularity attributes
CREATE OR REPLACE FUNCTION CREATE_VERSION (P_DATASET_OLD text,
										   P_DATASET_NEW text)
RETURNS void AS
$$
DECLARE
	VA_NEW_TABLE_NAME		text;
	VA_OLD_TABLE_NAME   text;
	VA_OLD_DATASET_ID   numeric;
	VA_NEW_DATASET_ID   numeric;
	VA_COUNTER			numeric;
BEGIN

	VA_NEW_TABLE_NAME := 'DATA_' || RANDOM_STRING(23);

	-- Obtenemos el nombre de la tabla vieja y el id
	SELECT ID, TABLE_NAME
	INTO VA_OLD_DATASET_ID, VA_OLD_TABLE_NAME
	FROM TB_DATASETS
	WHERE DATASET_ID = P_DATASET_OLD;

	VA_NEW_DATASET_ID := CLONE_TB_DATASETS(VA_OLD_DATASET_ID, P_DATASET_NEW, VA_NEW_TABLE_NAME);
	PERFORM CLONE_TB_DATASET_DIMENSIONS (VA_OLD_DATASET_ID, VA_NEW_DATASET_ID);
	PERFORM CLONE_TB_DATASET_ATTRIBUTES (VA_OLD_DATASET_ID, VA_NEW_DATASET_ID);
	PERFORM CLONE_TB_ATTRIBUTES(VA_OLD_DATASET_ID, VA_NEW_DATASET_ID);
	PERFORM CLONE_TB_GRANULARITY_ATTRIBUTES(VA_OLD_DATASET_ID, VA_NEW_DATASET_ID);
	PERFORM CLONE_OBSERVATIONS(VA_OLD_DATASET_ID, VA_OLD_TABLE_NAME, VA_NEW_TABLE_NAME);

	-- NOTE: Exception handling to delete possible elements created is not necessary, due to PostgreSQL ddl are transactional
END;
$$ LANGUAGE plpgsql;

commit;
