-- PENDIENTE ISTAC Lista de valores definitivos

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'kilometers', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'kilómetros', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_QUANTITIES_UNITS (ID, UUID, SYMBOL, SYMBOL_POSITION, TITLE_FK, VERSION) values (nextval('SEQ_QUANTITIES_UNITS'), '1', 'km', 'END', currval('SEQ_I18NSTRS'), 0);

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'meters', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'metros', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_QUANTITIES_UNITS (ID, UUID, SYMBOL, SYMBOL_POSITION, TITLE_FK, VERSION) values (nextval('SEQ_QUANTITIES_UNITS'), '2', 'm', 'END', currval('SEQ_I18NSTRS'), 0);
