
-- Unit multipliers
INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Unidades', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_UNITS_MULTIPLIERS (VERSION, ID, UNIT_MULTIPLIER, UUID, TITLE_FK) values (0, nextval('SEQ_UNITS_MULTIPLIERS'), 1, '1', currval('SEQ_I18NSTRS'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Decenas', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_UNITS_MULTIPLIERS (VERSION, ID, UNIT_MULTIPLIER, UUID, TITLE_FK) values (0, nextval('SEQ_UNITS_MULTIPLIERS'), 10, '2', currval('SEQ_I18NSTRS'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Cientos', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_UNITS_MULTIPLIERS (VERSION, ID, UNIT_MULTIPLIER, UUID, TITLE_FK) values (0, nextval('SEQ_UNITS_MULTIPLIERS'), 100, '3', currval('SEQ_I18NSTRS'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Miles', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_UNITS_MULTIPLIERS (VERSION, ID, UNIT_MULTIPLIER, UUID, TITLE_FK) values (0, nextval('SEQ_UNITS_MULTIPLIERS'), 1000, '4', currval('SEQ_I18NSTRS'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Decenas de miles', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_UNITS_MULTIPLIERS (VERSION, ID, UNIT_MULTIPLIER, UUID, TITLE_FK) values (0, nextval('SEQ_UNITS_MULTIPLIERS'), 10000, '5', currval('SEQ_I18NSTRS'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Cientos de miles', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_UNITS_MULTIPLIERS (VERSION, ID, UNIT_MULTIPLIER, UUID, TITLE_FK) values (0, nextval('SEQ_UNITS_MULTIPLIERS'), 100000, '6', currval('SEQ_I18NSTRS'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Millones', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_UNITS_MULTIPLIERS (VERSION, ID, UNIT_MULTIPLIER, UUID, TITLE_FK) values (0, nextval('SEQ_UNITS_MULTIPLIERS'), 1000000, '7', currval('SEQ_I18NSTRS'));
