-- ---------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- EDATOS-3494 - IBESTAT. Obtener el listado de la tabla de valores geográficos de eIndicadores
-- ---------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- Fichero elaborado a partir del fichero excel facilitado por el personal del IBESTAT
-- Enlace. https://trello.com/1/cards/61961452ec6b4f29253f5159/attachments/619e5a785b4e6c32722d33bf/download/Valores_geogr%C3%A1ficos.xlsx
-- 
-- Notas:
-- 1. Es necesario tener instalado la extensión uuid-ossp para la generación de los uuids de los elementos insertados 
-- -- Para ello es necesario ejecutar la siguiente sentencia como administrador de la bbdd CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
-- 2. Se añaden nuevos valores geográficos para comunidades autónomas, islas y municipios 
-- 3. Se actualizan literales y el valor del orden para algunos valores geográficos existentes previamente
-- ---------------------------------------------------------------------------------------------------------------------------------------------------------------------

----------------------------------------------------------------
-- Comunitats autònomes - 8
----------------------------------------------------------------
INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Illes Balears', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Balearic Islands', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Illes Balears', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), 'TT', '39.57114699', '2.65181698', 'ES_01ES53_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'REGIONS'));

----------------------------------------------------------------
-- Illes - 15
----------------------------------------------------------------
INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Menorca', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Minorca', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Menorca', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '2', '39.9488681', '3.7791066', 'ES_02ES533_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'ISLANDS'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Mallorca', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Majorca', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Mallorca', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '1', '39.6121517', '2.3512403', 'ES_01ES532_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'ISLANDS'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Eivissa', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Ibiza', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Eivissa', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '3', '38.907323', '1.3946285', 'ES_03ES531_072_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'ISLANDS'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Formentera', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Formentera', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Formentera', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '4', '38.7060245', '1.3423109', 'ES_04ES531_071_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'ISLANDS'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Eivissa i Formentera', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Ibiza y Formentera', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Eivissa i Formentera', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '5', null, null, 'ES_05ES531_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'ISLANDS'));


----------------------------------------------------------------
-- Municipis
----------------------------------------------------------------

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Es Migjorn Gran', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Es Migjorn Gran', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Es Migjorn Gran', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '2902', '39.9476226', '4.046003', 'ES_07902_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'MUNICIPALITIES'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Ariany', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Ariany', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Ariany', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '1901', '39.6510355', '3.1101702', 'ES_07901_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'MUNICIPALITIES'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Vilafranca de Bonany', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Vilafranca de Bonany', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Vilafranca de Bonany', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '1065', '39.5700463', '3.0843926', 'ES_07065_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'MUNICIPALITIES'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Es Castell', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Es Castell', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Es Castell', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '2064', '39.880066', '4.2876791', 'ES_07064_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'MUNICIPALITIES'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Valldemossa', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Valldemossa', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Valldemossa', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '1063', '39.711678', '2.622581', 'ES_07063_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'MUNICIPALITIES'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Son Servera', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Son Servera', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Son Servera', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '1062', '39.6221774', '3.3549047', 'ES_07062_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'MUNICIPALITIES'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Sóller', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Sóller', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Sóller', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '1061', '39.766667', '2.7', 'ES_07061_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'MUNICIPALITIES'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Sineu', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Sineu', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Sineu', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '1060', '39.6435847', '3.006648', 'ES_07060_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'MUNICIPALITIES'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Ses Salines', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Ses Salines', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Ses Salines', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '1059', '39.3384186', '3.0515226', 'ES_07059_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'MUNICIPALITIES'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Selva', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Selva', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Selva', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '1058', '39.754617', '2.8991724', 'ES_07058_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'MUNICIPALITIES'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Santanyí', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Santanyí', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Santanyí', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '1057', '39.3552529', '3.1253929', 'ES_07057_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'MUNICIPALITIES'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Santa Maria del Camí', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Santa Maria del Camí', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Santa Maria del Camí', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '1056', '39.651111', '2.773056', 'ES_07056_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'MUNICIPALITIES'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Santa Margalida', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Santa Margalida', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Santa Margalida', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '1055', '39.7025872', '3.0961157', 'ES_07055_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'MUNICIPALITIES'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Santa Eulària del Ríu', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Santa Eulària del Ríu', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Santa Eulària del Ríu', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '3054', '38.9865991', '1.5268277', 'ES_07054_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'MUNICIPALITIES'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Santa Eugènia', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Santa Eugènia', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Santa Eugènia', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '1053', '39.623936', '2.8363987', 'ES_07053_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'MUNICIPALITIES'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Sant Lluís', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Sant Lluís', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Sant Lluís', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '2052', '39.849444', '4.258056', 'ES_07052_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'MUNICIPALITIES'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Sant Llorenç des Cardassar', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Sant Llorenç des Cardassar', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Sant Llorenç des Cardassar', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '1051', '39.6126861', '3.2814498', 'ES_07051_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'MUNICIPALITIES'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Sant Joan de Labritja', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Sant Joan de Labritja', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Sant Joan de Labritja', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '3050', '39.078056', '1.511944', 'ES_07050_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'MUNICIPALITIES'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Sant Joan', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Sant Joan', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Sant Joan', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '1049', '39.5967749', '3.0354914', 'ES_07049_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'MUNICIPALITIES'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Sant Josep de sa Talaia', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Sant Josep de sa Talaia', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Sant Josep de sa Talaia', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '3048', '38.921667', '1.293333', 'ES_07048_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'MUNICIPALITIES'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Sencelles', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Sencelles', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Sencelles', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '1047', '39.6469175', '2.89494', 'ES_07047_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'MUNICIPALITIES'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Sant Antoni de Portmany', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Sant Antoni de Portmany', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Sant Antoni de Portmany', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '3046', '38.9823654', '1.2975279', 'ES_07046_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'MUNICIPALITIES'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Puigpunyent', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Puigpunyent', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Puigpunyent', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '1045', '39.622615', '2.527456', 'ES_07045_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'MUNICIPALITIES'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Sa Pobla', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Sa Pobla', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Sa Pobla', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '1044', '39.7697021', '3.0182507', 'ES_07044_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'MUNICIPALITIES'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Porreres', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Porreres', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Porreres', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '1043', '39.5145631', '3.0190294', 'ES_07043_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'MUNICIPALITIES'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Pollença', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Pollença', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Pollença', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '1042', '39.8763559', '3.0112472', 'ES_07042_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'MUNICIPALITIES'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Petra', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Petra', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Petra', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '1041', '39.6129275', '3.1099099', 'ES_07041_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'MUNICIPALITIES'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Palma', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Palma', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Palma', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '1040', '39.5700136', '2.6457357', 'ES_07040_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'MUNICIPALITIES'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Muro', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Muro', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Muro', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '1039', '39.7588332', '3.0472812', 'ES_07039_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'MUNICIPALITIES'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Montuïri', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Montuïri', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Montuïri', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '1038', '39.5667794', '2.9773898', 'ES_07038_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'MUNICIPALITIES'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Es Mercadal', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Es Mercadal', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Es Mercadal', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '2037', '39.9885116', '4.0875712', 'ES_07037_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'MUNICIPALITIES'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Marratxí', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Marratxí', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Marratxí', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '1036', '39.6214311', '2.6975034', 'ES_07036_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'MUNICIPALITIES'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Maria de la Salut', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Maria de la Salut', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Maria de la Salut', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '1035', '39.6656109', '3.0706344', 'ES_07035_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'MUNICIPALITIES'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Mancor de la Vall', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Mancor de la Vall', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Mancor de la Vall', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '1034', '39.7507003', '2.8676882', 'ES_07034_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'MUNICIPALITIES'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Manacor', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Manacor', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Manacor', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '1033', '39.5699649', '3.1975413', 'ES_07033_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'MUNICIPALITIES'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Maó', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Maó', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Maó', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '2032', '39.8876149', '4.2586722', 'ES_07032_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'MUNICIPALITIES'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Llucmajor', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Llucmajor', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Llucmajor', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '1031', '39.4522731', '2.7791882', 'ES_07031_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'MUNICIPALITIES'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Llubí', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Llubí', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Llubí', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '1030', '39.7012274', '3.0022125', 'ES_07030_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'MUNICIPALITIES'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Lloseta', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Lloseta', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Lloseta', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '1029', '39.7189962', '2.864232', 'ES_07029_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'MUNICIPALITIES'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Lloret de Vistalegre', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Lloret de Vistalegre', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Lloret de Vistalegre', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '1028', '39.6176351', '2.9700264', 'ES_07028_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'MUNICIPALITIES'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Inca', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Inca', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Inca', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '1027', '39.7202841', '2.9005836', 'ES_07027_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'MUNICIPALITIES'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Eivissa', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Ibiza', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Eivissa', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '3026', '38.908889', '1.432778', 'ES_07026_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'MUNICIPALITIES'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Fornalutx', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Fornalutx', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Fornalutx', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '1025', '39.7827482', '2.7392348', 'ES_07025_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'MUNICIPALITIES'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Formentera', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Formentera', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Formentera', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '4024', '38.7', '1.45', 'ES_07024_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'MUNICIPALITIES'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Ferreries', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Ferreries', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Ferreries', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '2023', '39.9825889', '4.0081475', 'ES_07023_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'MUNICIPALITIES'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Felanitx', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Felanitx', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Felanitx', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '1022', '39.4693552', '3.1408158', 'ES_07022_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'MUNICIPALITIES'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Estellencs', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Estellencs', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Estellencs', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '1021', '39.6532737', '2.4805354', 'ES_07021_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'MUNICIPALITIES'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Esporles', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Esporles', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Esporles', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '1020', '39.66202', '2.5540041', 'ES_07020_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'MUNICIPALITIES'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Escorca', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Escorca', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Escorca', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '1019', '39.8264133', '2.8455223', 'ES_07019_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'MUNICIPALITIES'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Deià', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Deià', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Deià', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '1018', '39.75', '2.633056', 'ES_07018_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'MUNICIPALITIES'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Costitx', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Costitx', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Costitx', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '1017', '39.6564124', '2.9450959', 'ES_07017_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'MUNICIPALITIES'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Consell', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Consell', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Consell', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '1016', '39.669076', '2.812157', 'ES_07016_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'MUNICIPALITIES'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Ciutadella de Menorca', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Ciutadella de Menorca', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Ciutadella de Menorca', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '2015', '40.001389', '3.836389', 'ES_07015_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'MUNICIPALITIES'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Capdepera', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Capdepera', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Capdepera', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '1014', '39.7025536', '3.4297389', 'ES_07014_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'MUNICIPALITIES'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Campos', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Campos', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Campos', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '1013', '39.4312564', '3.0150154', 'ES_07013_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'MUNICIPALITIES'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Campanet', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Campanet', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Campanet', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '1012', '39.7761583', '2.9598278', 'ES_07012_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'MUNICIPALITIES'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Calvià', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Calvià', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Calvià', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '1011', '39.566667', '2.516667', 'ES_07011_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'MUNICIPALITIES'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Bunyola', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Bunyola', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Bunyola', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '1010', '39.6962963', '2.6959685', 'ES_07010_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'MUNICIPALITIES'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Búger', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Búger', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Búger', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '1009', '39.758601', '2.9823916', 'ES_07009_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'MUNICIPALITIES'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Binissalem', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Binissalem', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Binissalem', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '1008', '39.6889863', '2.8344384', 'ES_07008_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'MUNICIPALITIES'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Banyalbufar', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Banyalbufar', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Banyalbufar', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '1007', '39.6872627', '2.514085', 'ES_07007_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'MUNICIPALITIES'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Artà', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Artà', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Artà', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '1006', '39.7299355', '3.3380711', 'ES_07006_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'MUNICIPALITIES'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Andratx', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Andratx', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Andratx', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '1005', '39.5733021', '2.4147438', 'ES_07005_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'MUNICIPALITIES'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Algaida', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Algaida', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Algaida', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '1004', '39.5594118', '2.8841363', 'ES_07004_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'MUNICIPALITIES'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Alcúdia', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Alcúdia', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Alcúdia', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '1003', '39.8530596', '3.1204613', 'ES_07003_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'MUNICIPALITIES'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Alaior', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Alaior', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Alaior', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '2002', '39.9336649', '4.1361728', 'ES_07002_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'MUNICIPALITIES'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Alaró', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Alaró', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Alaró', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '1001', '39.7068741', '2.7821922', 'ES_07001_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'MUNICIPALITIES'));

----------------------------------------------------------------
-- Comunitats autònomes
----------------------------------------------------------------

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Canàries', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Canary Islands', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Canarias', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '05', '28.2869925', '-15.8335245', 'ES_05ES70_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'REGIONS'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Ciutat Autònoma de Melilla', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Melilla', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Ciudad Autónoma de Melilla', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '19', '35.294731', '-2.942281', 'ES_19ES64_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'REGIONS'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Ciutats Autònomes de Ceuta i Melilla', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Ceuta y Melilla', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Ciudades Autónomas de Ceuta y Melilla', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '20', '35.88810209', '-5.30675127', 'ES_20ES63_ES64_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'REGIONS'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Ciutat Autònoma de Ceuta', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Ceuta', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Ciudad Autónoma de Ceuta', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '18', '35.88810209', '-5.30675127', 'ES_18ES63_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'REGIONS'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Múrcia (Regió de)', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Murcia', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Murcia (Región de)', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '14', '37.98436361', '-1.1285408', 'ES_14ES64_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'REGIONS'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Andalusia', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Andalusia', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Andalucía', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '02', '37.19354712', '-4.785234385', 'ES_02ES61_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'REGIONS'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Illes Balears', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Balearic Islands', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Illes Balears', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '01', '39.57114699', '2.65181698', 'ES_01ES53_2', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'REGIONS'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Comunitat Valenciana', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Valencia', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Comunitat Valenciana', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '10', '39.26907985', '-0.29857393', 'ES_10ES52_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'REGIONS'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Catalunya', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Catalonia', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Cataluña', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '09', '41.52512095', '1.719877375', 'ES_09ES51_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'REGIONS'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Extremadura', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Extremadura', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Extremadura', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '11', '39.17595551', '-6.67110398', 'ES_11ES43_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'REGIONS'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Castella-la Manxa', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Castile-La Mancha', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Castilla - La Mancha', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '08', '39.71008866', '-3.021001452', 'ES_08ES42_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'REGIONS'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Castella i Lleó', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Castile and Leon', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Castilla y León', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '07', '41.60399365', '-4.582083969', 'ES_07ES41_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'REGIONS'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Madrid (Comunitat de)', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Madrid', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Madrid (Comunidad de)', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '13', '40.40841191', '-3.68760088', 'ES_13ES30_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'REGIONS'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Aragó', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Aragon', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Aragón', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '03', '41.38040448', '-0.798993683', 'ES_03ES23_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'REGIONS'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'La Rioja', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'La Rioja', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'La Rioja', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '17', '42.46644945', '-2.44565538', 'ES_17ES23_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'REGIONS'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Navarra (Comunitat Foral de)', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Navarre', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Navarra (Comunidad Foral de)', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '15', '42.814102', '-1.6451528', 'ES_15ES22_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'REGIONS'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'País Basc', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Basque Country', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'País Vasco', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '16', '43.14165968', '-2.526193587', 'ES_16ES21_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'REGIONS'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Cantabria', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Cantabria', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Cantabria', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '06', '43.46297885', '-3.80474784', 'ES_06ES13_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'REGIONS'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Astúries (Principat d'')', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Asturias', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Asturias (Principado de)', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '04', '43.36232165', '-5.84372206', 'ES_04ES12_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'REGIONS'));

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (nextval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Galícia', 'ca', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Galicia', 'en', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (nextval('SEQ_L10NSTRS'), 'Galicia', 'es', currval('SEQ_I18NSTRS'), 1);
INSERT INTO TB_LIS_GEOGR_VALUES (VERSION, ID, CODE, LATITUDE, LONGITUDE, GLOBAL_ORDER, UUID, TITLE_FK, GRANULARITY_FK) values (0, nextval('SEQ_GEOGR_VALUES'), '12', '42.78740456', '-8.115249095', 'ES_12ES11_1', uuid_generate_v4(), currval('SEQ_I18NSTRS'), (select id from TB_LIS_GEOGR_GRANULARITIES where code  = 'REGIONS'));

----------------------------------------------------------------
-- Global order update
----------------------------------------------------------------

UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES_05ES70' WHERE CODE = 'ES70';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES_19ES64' WHERE CODE = 'ES64';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES_20ES63_ES64' WHERE CODE = 'ES63_ES64';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES_18ES63' WHERE CODE = 'ES63';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES_14ES64' WHERE CODE = 'ES62';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES_02ES61' WHERE CODE = 'ES61';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES_01ES53' WHERE CODE = 'ES53';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES_10ES52' WHERE CODE = 'ES52';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES_09ES51' WHERE CODE = 'ES51';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES_11ES43' WHERE CODE = 'ES43';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES_08ES42' WHERE CODE = 'ES42';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES_07ES41' WHERE CODE = 'ES41';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES_13ES30' WHERE CODE = 'ES30';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES_03ES23' WHERE CODE = 'ES24';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES_17ES23' WHERE CODE = 'ES23';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES_15ES22' WHERE CODE = 'ES22';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES_16ES21' WHERE CODE = 'ES21';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES_06ES13' WHERE CODE = 'ES13';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES_04ES12' WHERE CODE = 'ES12';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES_12ES11' WHERE CODE = 'ES11';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES_02ES533' WHERE CODE = 'ES533';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES_01ES532' WHERE CODE = 'ES532';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES_03ES531_072' WHERE CODE = 'ES531_072';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES_04ES531_071' WHERE CODE = 'ES531_071';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES_05ES531' WHERE CODE = 'ES531';

----------------------------------------------------------------
-- Labels update
----------------------------------------------------------------
UPDATE TB_LOCALISED_STRINGS SET LABEL = 'Comunitat Valenciana' WHERE LOCALE = 'es' AND INTERNATIONAL_STRING_FK = (SELECT TITLE_FK FROM TB_LIS_GEOGR_VALUES WHERE CODE = 'ES52');
UPDATE TB_LOCALISED_STRINGS SET LABEL = 'Madrid (Comunitat de)' WHERE LOCALE = 'ca' AND INTERNATIONAL_STRING_FK = (SELECT TITLE_FK FROM TB_LIS_GEOGR_VALUES WHERE CODE = 'ES30');
UPDATE TB_LOCALISED_STRINGS SET LABEL = 'Madrid (Comunidad de)' WHERE LOCALE = 'es' AND INTERNATIONAL_STRING_FK = (SELECT TITLE_FK FROM TB_LIS_GEOGR_VALUES WHERE CODE = 'ES30');
UPDATE TB_LOCALISED_STRINGS SET LABEL = 'Navarra (Comunitat Foral de)' WHERE LOCALE = 'ca' AND INTERNATIONAL_STRING_FK = (SELECT TITLE_FK FROM TB_LIS_GEOGR_VALUES WHERE CODE = 'ES22');
UPDATE TB_LOCALISED_STRINGS SET LABEL = 'Navarra (Comunidad Foral de)' WHERE LOCALE = 'es' AND INTERNATIONAL_STRING_FK = (SELECT TITLE_FK FROM TB_LIS_GEOGR_VALUES WHERE CODE = 'ES22');
UPDATE TB_LOCALISED_STRINGS SET LABEL = 'Astúries (Principat d'')' WHERE LOCALE = 'ca' AND INTERNATIONAL_STRING_FK = (SELECT TITLE_FK FROM TB_LIS_GEOGR_VALUES WHERE CODE = 'ES12');
UPDATE TB_LOCALISED_STRINGS SET LABEL = 'Asturias (Principado de)' WHERE LOCALE = 'es' AND INTERNATIONAL_STRING_FK = (SELECT TITLE_FK FROM TB_LIS_GEOGR_VALUES WHERE CODE = 'ES12');
UPDATE TB_LOCALISED_STRINGS SET LABEL = 'Múrcia (Regió de)' WHERE LOCALE = 'ca' AND INTERNATIONAL_STRING_FK = (SELECT TITLE_FK FROM TB_LIS_GEOGR_VALUES WHERE CODE = 'ES62');
UPDATE TB_LOCALISED_STRINGS SET LABEL = 'Murcia (Región de)' WHERE LOCALE = 'es' AND INTERNATIONAL_STRING_FK = (SELECT TITLE_FK FROM TB_LIS_GEOGR_VALUES WHERE CODE = 'ES62');
UPDATE TB_LOCALISED_STRINGS SET LABEL = 'Ceuta (Ciutat Autònoma de)' WHERE LOCALE = 'ca' AND INTERNATIONAL_STRING_FK = (SELECT TITLE_FK FROM TB_LIS_GEOGR_VALUES WHERE CODE = 'ES63');
UPDATE TB_LOCALISED_STRINGS SET LABEL = 'Ceuta (Ciudad Autónoma de)' WHERE LOCALE = 'es' AND INTERNATIONAL_STRING_FK = (SELECT TITLE_FK FROM TB_LIS_GEOGR_VALUES WHERE CODE = 'ES63');
UPDATE TB_LOCALISED_STRINGS SET LABEL = 'Ceuta i Melilla (Ciutats Autònomes de)' WHERE LOCALE = 'ca' AND INTERNATIONAL_STRING_FK = (SELECT TITLE_FK FROM TB_LIS_GEOGR_VALUES WHERE CODE = 'ES63_ES64');
UPDATE TB_LOCALISED_STRINGS SET LABEL = 'Ceuta and Melilla' WHERE LOCALE = 'en' AND INTERNATIONAL_STRING_FK = (SELECT TITLE_FK FROM TB_LIS_GEOGR_VALUES WHERE CODE = 'ES63_ES64');
UPDATE TB_LOCALISED_STRINGS SET LABEL = 'Ceuta y Melilla (Ciudades Autónomas de)' WHERE LOCALE = 'es' AND INTERNATIONAL_STRING_FK = (SELECT TITLE_FK FROM TB_LIS_GEOGR_VALUES WHERE CODE = 'ES63_ES64');
UPDATE TB_LOCALISED_STRINGS SET LABEL = 'Melilla (Ciutat Autònoma de)' WHERE LOCALE = 'ca' AND INTERNATIONAL_STRING_FK = (SELECT TITLE_FK FROM TB_LIS_GEOGR_VALUES WHERE CODE = 'ES64');
UPDATE TB_LOCALISED_STRINGS SET LABEL = 'Melilla (Ciudad Autónoma de)' WHERE LOCALE = 'es' AND INTERNATIONAL_STRING_FK = (SELECT TITLE_FK FROM TB_LIS_GEOGR_VALUES WHERE CODE = 'ES64');
UPDATE TB_LOCALISED_STRINGS SET LABEL = 'Ceuta (Ciutat Autònoma de)' WHERE LOCALE = 'ca' AND INTERNATIONAL_STRING_FK = (SELECT TITLE_FK FROM TB_LIS_GEOGR_VALUES WHERE CODE = '18');
UPDATE TB_LOCALISED_STRINGS SET LABEL = 'Ceuta (Ciudad Autónoma de)' WHERE LOCALE = 'es' AND INTERNATIONAL_STRING_FK = (SELECT TITLE_FK FROM TB_LIS_GEOGR_VALUES WHERE CODE = '18');
UPDATE TB_LOCALISED_STRINGS SET LABEL = 'Ceuta i Melilla (Ciutats Autònomes de)' WHERE LOCALE = 'ca' AND INTERNATIONAL_STRING_FK = (SELECT TITLE_FK FROM TB_LIS_GEOGR_VALUES WHERE CODE = '20');
UPDATE TB_LOCALISED_STRINGS SET LABEL = 'Ceuta and Melilla' WHERE LOCALE = 'en' AND INTERNATIONAL_STRING_FK = (SELECT TITLE_FK FROM TB_LIS_GEOGR_VALUES WHERE CODE = '20');
UPDATE TB_LOCALISED_STRINGS SET LABEL = 'Ceuta y Melilla (Ciudades Autónomas de)' WHERE LOCALE = 'es' AND INTERNATIONAL_STRING_FK = (SELECT TITLE_FK FROM TB_LIS_GEOGR_VALUES WHERE CODE = '20');
UPDATE TB_LOCALISED_STRINGS SET LABEL = 'Melilla (Ciutat Autònoma de)' WHERE LOCALE = 'ca' AND INTERNATIONAL_STRING_FK = (SELECT TITLE_FK FROM TB_LIS_GEOGR_VALUES WHERE CODE = '19');
UPDATE TB_LOCALISED_STRINGS SET LABEL = 'Melilla (Ciudad Autónoma de)' WHERE LOCALE = 'es' AND INTERNATIONAL_STRING_FK = (SELECT TITLE_FK FROM TB_LIS_GEOGR_VALUES WHERE CODE = '19');

commit;