
    
-- ###########################################
-- # Drop
-- ###########################################
-- Drop index
  
  


-- Drop many to many relations
    
-- Drop normal entities
    
DROP TABLE TBL_LOCALISED_STRINGS CASCADE CONSTRAINTS PURGE;

DROP TABLE TBL_INDIC_SYSTEMS_VERSIONS CASCADE CONSTRAINTS PURGE;

DROP TABLE TBL_INTERNATIONAL_STRINGS CASCADE CONSTRAINTS PURGE;

DROP TABLE TBL_INDICATORS_SYSTEMS CASCADE CONSTRAINTS PURGE;


-- Drop pk sequence
    
drop sequence hibernate_sequence;


-- ###########################################
-- # Create
-- ###########################################
-- Create pk sequence
    
create sequence hibernate_sequence;


-- Create normal entities
    
CREATE TABLE TBL_INDICATORS_SYSTEMS (
  ID NUMBER(19) NOT NULL,
  CODE VARCHAR2(100) NOT NULL,
  UUID VARCHAR2(36) NOT NULL,
  CREATED_DATE_TZ VARCHAR2(50),
  CREATED_DATE TIMESTAMP,
  CREATED_BY VARCHAR2(50),
  LAST_UPDATED_TZ VARCHAR2(50),
  LAST_UPDATED TIMESTAMP,
  LAST_UPDATED_BY VARCHAR2(50),
  VERSION NUMBER(19) NOT NULL,
  DRAFT_ID NUMBER(19),
  DRAFT_VERSION_NUMBER NUMBER(19),
  PUBLISHED_ID NUMBER(19),
  PUBLISHED_VERSION_NUMBER NUMBER(19)
);


CREATE TABLE TBL_INTERNATIONAL_STRINGS (
  ID NUMBER(19) NOT NULL,
  UUID VARCHAR2(36) NOT NULL,
  VERSION NUMBER(19) NOT NULL
);


CREATE TABLE TBL_INDIC_SYSTEMS_VERSIONS (
  ID NUMBER(19) NOT NULL,
  VERSION_NUMBER NUMBER(19) NOT NULL,
  URI VARCHAR2(100),
  PUBLISHING_DATE_TZ VARCHAR2(50),
  PUBLISHING_DATE TIMESTAMP,
  UNPUBLISHING_DATE_TZ VARCHAR2(50),
  UNPUBLISHING_DATE TIMESTAMP,
  UUID VARCHAR2(36) NOT NULL,
  CREATED_DATE_TZ VARCHAR2(50),
  CREATED_DATE TIMESTAMP,
  CREATED_BY VARCHAR2(50),
  LAST_UPDATED_TZ VARCHAR2(50),
  LAST_UPDATED TIMESTAMP,
  LAST_UPDATED_BY VARCHAR2(50),
  VERSION NUMBER(19) NOT NULL,
  TITLE_FK NUMBER(19) NOT NULL,
  ACRONYM_FK NUMBER(19),
  OBJETIVE_FK NUMBER(19),
  DESCRIPTION_FK NUMBER(19),
  INDICATORS_SYSTEMS_FK NUMBER(19) NOT NULL,
  STATE VARCHAR2(40) NOT NULL
);


CREATE TABLE TBL_LOCALISED_STRINGS (
  ID NUMBER(19) NOT NULL,
  LABEL VARCHAR2(4000) NOT NULL,
  LOCALE VARCHAR2(100) NOT NULL,
  UUID VARCHAR2(36) NOT NULL,
  VERSION NUMBER(19) NOT NULL,
  INTERNATIONAL_STRING_FK NUMBER(19)
);



-- Create many to many relations
    

-- Primary keys
    
ALTER TABLE TBL_INDICATORS_SYSTEMS ADD CONSTRAINT PK_TBL_INDICATORS_SYSTEMS
	PRIMARY KEY (ID)
;

ALTER TABLE TBL_INTERNATIONAL_STRINGS ADD CONSTRAINT PK_TBL_INTERNATIONAL_STRINGS
	PRIMARY KEY (ID)
;

ALTER TABLE TBL_INDIC_SYSTEMS_VERSIONS ADD CONSTRAINT PK_TBL_INDIC_SYSTEMS_VERSIONS
	PRIMARY KEY (ID)
;

ALTER TABLE TBL_LOCALISED_STRINGS ADD CONSTRAINT PK_TBL_LOCALISED_STRINGS
	PRIMARY KEY (ID)
;

    

-- Unique constraints

ALTER TABLE TBL_INDICATORS_SYSTEMS
    ADD CONSTRAINT UQ_TBL_INDICATORS_SYSTEMS UNIQUE (UUID)
;


ALTER TABLE TBL_INTERNATIONAL_STRINGS
    ADD CONSTRAINT UQ_TBL_INTERNATIONAL_STRINGS UNIQUE (UUID)
;


ALTER TABLE TBL_INDIC_SYSTEMS_VERSIONS
    ADD CONSTRAINT UQ_TBL_INDIC_SYSTEMS_VERSIONS UNIQUE (UUID)
;


ALTER TABLE TBL_LOCALISED_STRINGS
    ADD CONSTRAINT UQ_TBL_LOCALISED_STRINGS UNIQUE (UUID)
;



-- Foreign key constraints
    

  
  
  
ALTER TABLE TBL_LOCALISED_STRINGS ADD CONSTRAINT FK_TBL_LOCALISED_STRINGS_TBL13
	FOREIGN KEY (INTERNATIONAL_STRING_FK) REFERENCES TBL_INTERNATIONAL_STRINGS (ID)
;

ALTER TABLE TBL_INDIC_SYSTEMS_VERSIONS ADD CONSTRAINT FK_TBL_INDIC_SYSTEMS_VERSION90
	FOREIGN KEY (TITLE_FK) REFERENCES TBL_INTERNATIONAL_STRINGS (ID)
;
ALTER TABLE TBL_INDIC_SYSTEMS_VERSIONS ADD CONSTRAINT FK_TBL_INDIC_SYSTEMS_VERSION13
	FOREIGN KEY (ACRONYM_FK) REFERENCES TBL_INTERNATIONAL_STRINGS (ID)
;
ALTER TABLE TBL_INDIC_SYSTEMS_VERSIONS ADD CONSTRAINT FK_TBL_INDIC_SYSTEMS_VERSION56
	FOREIGN KEY (OBJETIVE_FK) REFERENCES TBL_INTERNATIONAL_STRINGS (ID)
;
ALTER TABLE TBL_INDIC_SYSTEMS_VERSIONS ADD CONSTRAINT FK_TBL_INDIC_SYSTEMS_VERSION98
	FOREIGN KEY (DESCRIPTION_FK) REFERENCES TBL_INTERNATIONAL_STRINGS (ID)
;
ALTER TABLE TBL_INDIC_SYSTEMS_VERSIONS ADD CONSTRAINT FK_TBL_INDIC_SYSTEMS_VERSION67
	FOREIGN KEY (INDICATORS_SYSTEMS_FK) REFERENCES TBL_INDICATORS_SYSTEMS (ID)
;

  
  
  

    

-- Index
  
  


    