-- Create normal entities
    
CREATE TABLE TBL_INTERNATIONAL_STRINGS (
  ID NUMBER(19) NOT NULL,
  UUID VARCHAR2(36) NOT NULL,
  VERSION NUMBER(19) NOT NULL
);


CREATE TABLE TBL_INDICATORS (
  ID NUMBER(19) NOT NULL,
  CODE VARCHAR2(100) NOT NULL,
  UUID VARCHAR2(36) NOT NULL,
  CREATED_DATE_TZ VARCHAR2(50),
  CREATED_DATE TIMESTAMP,
  CREATED_BY VARCHAR2(50),
  LAST_UPDATED_TZ VARCHAR2(50),
  LAST_UPDATED TIMESTAMP,
  LAST_UPDATED_BY VARCHAR2(50),
  VERSION NUMBER(19) NOT NULL,
  PRODUCTION_ID NUMBER(19),
  PRODUCTION_VERSION_NUMBER VARCHAR2(10),
  DIFFUSION_ID NUMBER(19),
  DIFFUSION_VERSION_NUMBER VARCHAR2(10)
);


CREATE TABLE TBL_INDICATORS_VERSIONS (
  ID NUMBER(19) NOT NULL,
  VERSION_NUMBER VARCHAR2(10) NOT NULL,
  SUBJECT_CODE VARCHAR2(100),
  NOTE_URL VARCHAR2(100),
  PRODUCTION_VALIDATION_DATE_TZ VARCHAR2(50),
  PRODUCTION_VALIDATION_DATE TIMESTAMP,
  PRODUCTION_VALIDATION_USER VARCHAR2(100),
  DIFFUSION_VALIDATION_DATE_TZ VARCHAR2(50),
  DIFFUSION_VALIDATION_DATE TIMESTAMP,
  DIFFUSION_VALIDATION_USER VARCHAR2(100),
  PUBLICATION_DATE_TZ VARCHAR2(50),
  PUBLICATION_DATE TIMESTAMP,
  PUBLICATION_USER VARCHAR2(100),
  ARCHIVE_DATE_TZ VARCHAR2(50),
  ARCHIVE_DATE TIMESTAMP,
  ARCHIVE_USER VARCHAR2(100),
  UUID VARCHAR2(36) NOT NULL,
  CREATED_DATE_TZ VARCHAR2(50),
  CREATED_DATE TIMESTAMP,
  CREATED_BY VARCHAR2(50),
  LAST_UPDATED_TZ VARCHAR2(50),
  LAST_UPDATED TIMESTAMP,
  LAST_UPDATED_BY VARCHAR2(50),
  VERSION NUMBER(19) NOT NULL,
  NAME_FK NUMBER(19) NOT NULL,
  ACRONYM_FK NUMBER(19),
  COMMENTARY_FK NUMBER(19),
  NOTES_FK NUMBER(19),
  INDICATOR_FK NUMBER(19) NOT NULL,
  STATE VARCHAR2(40) NOT NULL
);


CREATE TABLE TBL_DATA_SOURCES (
  ID NUMBER(19) NOT NULL,
  QUERY_GPE VARCHAR2(100) NOT NULL,
  PX VARCHAR2(100) NOT NULL,
  TEMPORARY_VARIABLE VARCHAR2(100) NOT NULL,
  GEOGRAPHIC_VARIABLE VARCHAR2(100) NOT NULL,
  UUID VARCHAR2(36) NOT NULL,
  CREATED_DATE_TZ VARCHAR2(50),
  CREATED_DATE TIMESTAMP,
  CREATED_BY VARCHAR2(50),
  LAST_UPDATED_TZ VARCHAR2(50),
  LAST_UPDATED TIMESTAMP,
  LAST_UPDATED_BY VARCHAR2(50),
  VERSION NUMBER(19) NOT NULL,
  INDICATOR_VERSION_FK NUMBER(19)
);


CREATE TABLE TBL_DATA_SOURCES_VARIABLES (
  ID NUMBER(19) NOT NULL,
  VARIABLE VARCHAR2(100) NOT NULL,
  CATEGORY VARCHAR2(100) NOT NULL,
  UUID VARCHAR2(36) NOT NULL,
  CREATED_DATE_TZ VARCHAR2(50),
  CREATED_DATE TIMESTAMP,
  CREATED_BY VARCHAR2(50),
  LAST_UPDATED_TZ VARCHAR2(50),
  LAST_UPDATED TIMESTAMP,
  LAST_UPDATED_BY VARCHAR2(50),
  VERSION NUMBER(19) NOT NULL,
  DATA_SOURCE_FK NUMBER(19)
);


CREATE TABLE TBL_INDICATORS_INSTANCES (
  ID NUMBER(19) NOT NULL,
  TEMPORARY_GRANULARITY_ID VARCHAR2(100),
  TEMPORARY_VALUE VARCHAR2(100),
  GEOGRAPHIC_GRANULARITY_ID VARCHAR2(100),
  GEOGRAPHIC_VALUE VARCHAR2(100),
  UUID VARCHAR2(36) NOT NULL,
  CREATED_DATE_TZ VARCHAR2(50),
  CREATED_DATE TIMESTAMP,
  CREATED_BY VARCHAR2(50),
  LAST_UPDATED_TZ VARCHAR2(50),
  LAST_UPDATED TIMESTAMP,
  LAST_UPDATED_BY VARCHAR2(50),
  VERSION NUMBER(19) NOT NULL,
  TITLE_FK NUMBER(19) NOT NULL,
  INDICATOR_FK NUMBER(19) NOT NULL
);


CREATE TABLE TBL_INDICATORS_SYSTEMS (
  ID NUMBER(19) NOT NULL,
  CODE VARCHAR2(100) NOT NULL,
  UUID VARCHAR2(36) NOT NULL,
  CREATED_DATE_TZ VARCHAR2(50),
  CREATED_DATE TIMESTAMP,
  CREATED_BY VARCHAR2(50),
  LAST_UPDATED_TZ VARCHAR2(50),
  LAST_UPDATED TIMESTAMP,
  LAST_UPDATED_BY VARCHAR2(50),
  VERSION NUMBER(19) NOT NULL,
  PRODUCTION_ID NUMBER(19),
  PRODUCTION_VERSION_NUMBER VARCHAR2(10),
  DIFFUSION_ID NUMBER(19),
  DIFFUSION_VERSION_NUMBER VARCHAR2(10)
);


CREATE TABLE TBL_INDIC_SYSTEMS_VERSIONS (
  ID NUMBER(19) NOT NULL,
  VERSION_NUMBER VARCHAR2(10) NOT NULL,
  URI_GOPESTAT VARCHAR2(100),
  PRODUCTION_VALIDATION_DATE_TZ VARCHAR2(50),
  PRODUCTION_VALIDATION_DATE TIMESTAMP,
  PRODUCTION_VALIDATION_USER VARCHAR2(100),
  DIFFUSION_VALIDATION_DATE_TZ VARCHAR2(50),
  DIFFUSION_VALIDATION_DATE TIMESTAMP,
  DIFFUSION_VALIDATION_USER VARCHAR2(100),
  PUBLICATION_DATE_TZ VARCHAR2(50),
  PUBLICATION_DATE TIMESTAMP,
  PUBLICATION_USER VARCHAR2(100),
  ARCHIVE_DATE_TZ VARCHAR2(50),
  ARCHIVE_DATE TIMESTAMP,
  ARCHIVE_USER VARCHAR2(100),
  UUID VARCHAR2(36) NOT NULL,
  CREATED_DATE_TZ VARCHAR2(50),
  CREATED_DATE TIMESTAMP,
  CREATED_BY VARCHAR2(50),
  LAST_UPDATED_TZ VARCHAR2(50),
  LAST_UPDATED TIMESTAMP,
  LAST_UPDATED_BY VARCHAR2(50),
  VERSION NUMBER(19) NOT NULL,
  TITLE_FK NUMBER(19) NOT NULL,
  ACRONYM_FK NUMBER(19),
  OBJETIVE_FK NUMBER(19),
  DESCRIPTION_FK NUMBER(19),
  INDICATORS_SYSTEM_FK NUMBER(19) NOT NULL,
  STATE VARCHAR2(40) NOT NULL
);


CREATE TABLE TBL_ELEMENTS_LEVELS (
  ID NUMBER(19) NOT NULL,
  ORDER_IN_LEVEL NUMBER(19) NOT NULL,
  UUID VARCHAR2(36) NOT NULL,
  VERSION NUMBER(19) NOT NULL,
  PARENT_FK NUMBER(19),
  DIMENSION_FK NUMBER(19),
  INDICATOR_INSTANCE_FK NUMBER(19),
  IND_SYSTEM_VERSION_ALL_FK NUMBER(19) NOT NULL,
  IND_SYSTEM_VERSION_FIRST_FK NUMBER(19)
);


CREATE TABLE TBL_DIMENSIONS (
  ID NUMBER(19) NOT NULL,
  UUID VARCHAR2(36) NOT NULL,
  CREATED_DATE_TZ VARCHAR2(50),
  CREATED_DATE TIMESTAMP,
  CREATED_BY VARCHAR2(50),
  LAST_UPDATED_TZ VARCHAR2(50),
  LAST_UPDATED TIMESTAMP,
  LAST_UPDATED_BY VARCHAR2(50),
  VERSION NUMBER(19) NOT NULL,
  TITLE_FK NUMBER(19) NOT NULL
);


CREATE TABLE TBL_LOCALISED_STRINGS (
  ID NUMBER(19) NOT NULL,
  LABEL VARCHAR2(4000) NOT NULL,
  LOCALE VARCHAR2(100) NOT NULL,
  UUID VARCHAR2(36) NOT NULL,
  VERSION NUMBER(19) NOT NULL,
  INTERNATIONAL_STRING_FK NUMBER(19)
);



-- Create many to many relations
    

-- Primary keys
    
ALTER TABLE TBL_INTERNATIONAL_STRINGS ADD CONSTRAINT PK_TBL_INTERNATIONAL_STRINGS
	PRIMARY KEY (ID)
;

ALTER TABLE TBL_INDICATORS ADD CONSTRAINT PK_TBL_INDICATORS
	PRIMARY KEY (ID)
;

ALTER TABLE TBL_INDICATORS_VERSIONS ADD CONSTRAINT PK_TBL_INDICATORS_VERSIONS
	PRIMARY KEY (ID)
;

ALTER TABLE TBL_DATA_SOURCES ADD CONSTRAINT PK_TBL_DATA_SOURCES
	PRIMARY KEY (ID)
;

ALTER TABLE TBL_DATA_SOURCES_VARIABLES ADD CONSTRAINT PK_TBL_DATA_SOURCES_VARIABLES
	PRIMARY KEY (ID)
;

ALTER TABLE TBL_INDICATORS_INSTANCES ADD CONSTRAINT PK_TBL_INDICATORS_INSTANCES
	PRIMARY KEY (ID)
;

ALTER TABLE TBL_INDICATORS_SYSTEMS ADD CONSTRAINT PK_TBL_INDICATORS_SYSTEMS
	PRIMARY KEY (ID)
;

ALTER TABLE TBL_INDIC_SYSTEMS_VERSIONS ADD CONSTRAINT PK_TBL_INDIC_SYSTEMS_VERSIONS
	PRIMARY KEY (ID)
;

ALTER TABLE TBL_ELEMENTS_LEVELS ADD CONSTRAINT PK_TBL_ELEMENTS_LEVELS
	PRIMARY KEY (ID)
;

ALTER TABLE TBL_DIMENSIONS ADD CONSTRAINT PK_TBL_DIMENSIONS
	PRIMARY KEY (ID)
;

ALTER TABLE TBL_LOCALISED_STRINGS ADD CONSTRAINT PK_TBL_LOCALISED_STRINGS
	PRIMARY KEY (ID)
;

    

-- Unique constraints

ALTER TABLE TBL_INTERNATIONAL_STRINGS
    ADD CONSTRAINT UQ_TBL_INTERNATIONAL_STRINGS UNIQUE (UUID)
;


ALTER TABLE TBL_INDICATORS
    ADD CONSTRAINT UQ_TBL_INDICATORS UNIQUE (UUID)
;


ALTER TABLE TBL_INDICATORS_VERSIONS
    ADD CONSTRAINT UQ_TBL_INDICATORS_VERSIONS UNIQUE (UUID)
;


ALTER TABLE TBL_DATA_SOURCES
    ADD CONSTRAINT UQ_TBL_DATA_SOURCES UNIQUE (UUID)
;


ALTER TABLE TBL_DATA_SOURCES_VARIABLES
    ADD CONSTRAINT UQ_TBL_DATA_SOURCES_VARIABLES UNIQUE (UUID)
;


ALTER TABLE TBL_INDICATORS_INSTANCES
    ADD CONSTRAINT UQ_TBL_INDICATORS_INSTANCES UNIQUE (UUID)
;


ALTER TABLE TBL_INDICATORS_SYSTEMS
    ADD CONSTRAINT UQ_TBL_INDICATORS_SYSTEMS UNIQUE (UUID)
;


ALTER TABLE TBL_INDIC_SYSTEMS_VERSIONS
    ADD CONSTRAINT UQ_TBL_INDIC_SYSTEMS_VERSIONS UNIQUE (UUID)
;


ALTER TABLE TBL_ELEMENTS_LEVELS
    ADD CONSTRAINT UQ_TBL_ELEMENTS_LEVELS UNIQUE (UUID)
;


ALTER TABLE TBL_DIMENSIONS
    ADD CONSTRAINT UQ_TBL_DIMENSIONS UNIQUE (UUID)
;


ALTER TABLE TBL_LOCALISED_STRINGS
    ADD CONSTRAINT UQ_TBL_LOCALISED_STRINGS UNIQUE (UUID)
;



-- Foreign key constraints
    

  
ALTER TABLE TBL_LOCALISED_STRINGS ADD CONSTRAINT FK_TBL_LOCALISED_STRINGS_TBL13
	FOREIGN KEY (INTERNATIONAL_STRING_FK) REFERENCES TBL_INTERNATIONAL_STRINGS (ID)
;

  
  
ALTER TABLE TBL_INDICATORS_VERSIONS ADD CONSTRAINT FK_TBL_INDICATORS_VERSIONS_N53
	FOREIGN KEY (NAME_FK) REFERENCES TBL_INTERNATIONAL_STRINGS (ID)
;
ALTER TABLE TBL_INDICATORS_VERSIONS ADD CONSTRAINT FK_TBL_INDICATORS_VERSIONS_A27
	FOREIGN KEY (ACRONYM_FK) REFERENCES TBL_INTERNATIONAL_STRINGS (ID)
;
ALTER TABLE TBL_INDICATORS_VERSIONS ADD CONSTRAINT FK_TBL_INDICATORS_VERSIONS_C89
	FOREIGN KEY (COMMENTARY_FK) REFERENCES TBL_INTERNATIONAL_STRINGS (ID)
;
ALTER TABLE TBL_INDICATORS_VERSIONS ADD CONSTRAINT FK_TBL_INDICATORS_VERSIONS_N77
	FOREIGN KEY (NOTES_FK) REFERENCES TBL_INTERNATIONAL_STRINGS (ID)
;
ALTER TABLE TBL_INDICATORS_VERSIONS ADD CONSTRAINT FK_TBL_INDICATORS_VERSIONS_I59
	FOREIGN KEY (INDICATOR_FK) REFERENCES TBL_INDICATORS (ID)
;

  
ALTER TABLE TBL_DATA_SOURCES ADD CONSTRAINT FK_TBL_DATA_SOURCES_INDICATO27
	FOREIGN KEY (INDICATOR_VERSION_FK) REFERENCES TBL_INDICATORS_VERSIONS (ID)
;

ALTER TABLE TBL_DATA_SOURCES_VARIABLES ADD CONSTRAINT FK_TBL_DATA_SOURCES_VARIABLE65
	FOREIGN KEY (DATA_SOURCE_FK) REFERENCES TBL_DATA_SOURCES (ID)
;

  
  
ALTER TABLE TBL_INDICATORS_INSTANCES ADD CONSTRAINT FK_TBL_INDICATORS_INSTANCES_99
	FOREIGN KEY (TITLE_FK) REFERENCES TBL_INTERNATIONAL_STRINGS (ID)
;
ALTER TABLE TBL_INDICATORS_INSTANCES ADD CONSTRAINT FK_TBL_INDICATORS_INSTANCES_40
	FOREIGN KEY (INDICATOR_FK) REFERENCES TBL_INDICATORS (ID)
;

  
  
  
ALTER TABLE TBL_INDIC_SYSTEMS_VERSIONS ADD CONSTRAINT FK_TBL_INDIC_SYSTEMS_VERSION90
	FOREIGN KEY (TITLE_FK) REFERENCES TBL_INTERNATIONAL_STRINGS (ID)
;
ALTER TABLE TBL_INDIC_SYSTEMS_VERSIONS ADD CONSTRAINT FK_TBL_INDIC_SYSTEMS_VERSION13
	FOREIGN KEY (ACRONYM_FK) REFERENCES TBL_INTERNATIONAL_STRINGS (ID)
;
ALTER TABLE TBL_INDIC_SYSTEMS_VERSIONS ADD CONSTRAINT FK_TBL_INDIC_SYSTEMS_VERSION56
	FOREIGN KEY (OBJETIVE_FK) REFERENCES TBL_INTERNATIONAL_STRINGS (ID)
;
ALTER TABLE TBL_INDIC_SYSTEMS_VERSIONS ADD CONSTRAINT FK_TBL_INDIC_SYSTEMS_VERSION98
	FOREIGN KEY (DESCRIPTION_FK) REFERENCES TBL_INTERNATIONAL_STRINGS (ID)
;
ALTER TABLE TBL_INDIC_SYSTEMS_VERSIONS ADD CONSTRAINT FK_TBL_INDIC_SYSTEMS_VERSION60
	FOREIGN KEY (INDICATORS_SYSTEM_FK) REFERENCES TBL_INDICATORS_SYSTEMS (ID)
;

  
ALTER TABLE TBL_ELEMENTS_LEVELS ADD CONSTRAINT FK_TBL_ELEMENTS_LEVELS_PAREN61
	FOREIGN KEY (PARENT_FK) REFERENCES TBL_ELEMENTS_LEVELS (ID)
;
ALTER TABLE TBL_ELEMENTS_LEVELS ADD CONSTRAINT FK_TBL_ELEMENTS_LEVELS_DIMEN43
	FOREIGN KEY (DIMENSION_FK) REFERENCES TBL_DIMENSIONS (ID)
;
ALTER TABLE TBL_ELEMENTS_LEVELS ADD CONSTRAINT FK_TBL_ELEMENTS_LEVELS_INDIC58
	FOREIGN KEY (INDICATOR_INSTANCE_FK) REFERENCES TBL_INDICATORS_INSTANCES (ID)
;
ALTER TABLE TBL_ELEMENTS_LEVELS ADD CONSTRAINT FK_TBL_ELEMENTS_LEVELS_IND_S25
	FOREIGN KEY (IND_SYSTEM_VERSION_ALL_FK) REFERENCES TBL_INDIC_SYSTEMS_VERSIONS (ID)
;
ALTER TABLE TBL_ELEMENTS_LEVELS ADD CONSTRAINT FK_TBL_ELEMENTS_LEVELS_IND_S06
	FOREIGN KEY (IND_SYSTEM_VERSION_FIRST_FK) REFERENCES TBL_INDIC_SYSTEMS_VERSIONS (ID)
;

  
ALTER TABLE TBL_DIMENSIONS ADD CONSTRAINT FK_TBL_DIMENSIONS_TITLE_FK
	FOREIGN KEY (TITLE_FK) REFERENCES TBL_INTERNATIONAL_STRINGS (ID)
;

  
  
  

    

-- Index
  
  
  
  


