ALTER TABLE TB_LOCALISED_STRINGS ADD CONSTRAINT LOCALE_INTERNATIONAL UNIQUE(LOCALE, INTERNATIONAL_STRING_FK) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE TB_INDICATORS_SYSTEMS ADD CONSTRAINT INDICATORS_SYSTEMS_CODE UNIQUE(CODE);
ALTER TABLE TB_INDICATORS ADD CONSTRAINT INDICATORS_CODE UNIQUE(CODE);
ALTER TABLE TB_INDICATORS_VERSIONS ADD CONSTRAINT INDICATORS_DATA_REP_ID UNIQUE(DATA_REPOSITORY_ID);
ALTER TABLE TB_INDICATORS_VERSIONS ADD CONSTRAINT INDICATORS_DATA_REP_TN UNIQUE(DATA_REPOSITORY_TABLE_NAME);
ALTER TABLE TB_ELEMENTS_LEVELS ADD CONSTRAINT ORDERS_UNIQUE UNIQUE(ORDER_IN_LEVEL, IND_SYSTEM_VERSION_FIRST_FK, PARENT_FK) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE TB_LIS_GEOGR_VALUES ADD CONSTRAINT GEOGR_VALUES_CODE UNIQUE(CODE);
ALTER TABLE TB_LIS_GEOGR_GRANULARITIES ADD CONSTRAINT GEOGR_GRANULARITIES_CODE UNIQUE(CODE);
ALTER TABLE TB_TRANSLATIONS ADD CONSTRAINT TRANSLATIONS_CODE UNIQUE(CODE);