-- En el Istac será una vista de una tabla

CREATE TABLE TV_CATALOGO_OPERACION_ESTADIST (
  ID_CATALOGO VARCHAR2(15 BYTE) NOT NULL,
  DESCRIPCION VARCHAR2(200 BYTE) NOT NULL
);

ALTER TABLE TV_CATALOGO_OPERACION_ESTADIST ADD CONSTRAINT PK_TV_CATALOGO_OPER_ESTADIST
  PRIMARY KEY (ID_CATALOGO)
;
