ALTER TABLE TBL_LOCALISED_STRINGS ADD CONSTRAINT LOCALE_INTERNATIONAL UNIQUE(LOCALE, INTERNATIONAL_STRING_FK) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE TBL_INDICATORS_SYSTEMS ADD CONSTRAINT INDICATORS_SYSTEMS_CODE UNIQUE(CODE);
ALTER TABLE TBL_INDICATORS ADD CONSTRAINT INDICATORS_CODE UNIQUE(CODE);
ALTER TABLE TBL_DIMENSIONS ADD CONSTRAINT DIMENSIONS_ORDERS_UNIQUE UNIQUE(ORDER_IN_LEVEL, INDICATORS_SYSTEM_VERSION_FK, PARENT_FK) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE TBL_INDICATOR_INSTANCES ADD CONSTRAINT INSTANCES_PARENT_UNIQUE UNIQUE(INDICATOR_UUID, INDICATORS_SYSTEM_VERSION_FK, DIMENSION_FK) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE TBL_INDICATOR_INSTANCES ADD CONSTRAINT INSTANCES_ORDERS_UNIQUE UNIQUE(ORDER_IN_LEVEL, DIMENSION_FK) DEFERRABLE INITIALLY DEFERRED;