-- En el Istac será una vista de una tabla

-- Creación de la vista en el ISTAC:
-- CREATE OR REPLACE FORCE VIEW tv_areas_tematicas (id_area_tematica,descripcion) AS SELECT id_catalogo, descripcion FROM tb_catalogo_operacion_estadist;
-- Area tematica
CREATE TABLE TV_AREAS_TEMATICAS (
  ID_AREA_TEMATICA VARCHAR2(15 BYTE) NOT NULL,
  DESCRIPCION VARCHAR2(200 BYTE) NOT NULL
);

ALTER TABLE TV_AREAS_TEMATICAS ADD CONSTRAINT PK_TV_AREAS_TEMATICAS
  PRIMARY KEY (ID_AREA_TEMATICA)
;

-- Consultas del gpe
CREATE TABLE TV_CONSULTA (
  ID_CONSULTA NUMBER(19) NOT NULL,
  UUID_CONSULTA VARCHAR2(255),
  NOMBRE_CONSULTA VARCHAR2(255),
  TIPO_CONSULTA VARCHAR2(255),
  CONSULTA CLOB,
  URI_PX VARCHAR2(255) NOT NULL,
  VERSION_PX VARCHAR2(255),
  ID_OPERACION VARCHAR2(7) NOT NULL,
  USUARIO_CREACION VARCHAR2(255) NOT NULL,
  FECHA_CREACION DATE NOT NULL,
  USUARIO_MODIFICACION VARCHAR2(255),
  FECHA_MODIFICACION DATE,
  FECHA_MODIFICACION_DATOS DATE,
  AUTOINCREMENTO VARCHAR2(100),
  FECHA_DISPONIBLE_INICIO DATE,
  FECHA_DISPONIBLE_FIN DATE,
  IS_PART_OF CLOB
);

ALTER TABLE TV_CONSULTA ADD CONSTRAINT PK_TV_CONSULTA
  PRIMARY KEY (ID_CONSULTA)
;