ALTER TABLE TBL_LOCALISED_STRINGS ADD CONSTRAINT LOCALE_INTERNATIONAL UNIQUE(LOCALE, INTERNATIONAL_STRING_FK) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE TBL_INDICATORS_SYSTEMS ADD CONSTRAINT INDICATORS_SYSTEMS_CODE UNIQUE(CODE);
ALTER TABLE TBL_INDICATORS ADD CONSTRAINT INDICATORS_CODE UNIQUE(CODE);
ALTER TABLE TBL_ELEMENTS_LEVELS ADD CONSTRAINT ORDERS_UNIQUE UNIQUE(ORDER_IN_LEVEL, IND_SYSTEM_VERSION_FIRST_FK, PARENT_FK) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE LIS_GEOGR_VALUES ADD CONSTRAINT GEOGR_VALUES_CODE UNIQUE(CODE);
ALTER TABLE LIS_GEOGR_GRANULARITIES ADD CONSTRAINT GEOGR_GRANULARITIES_CODE UNIQUE(CODE);