DROP sequence hibernate_sequence;

CREATE sequence SEQ_INDIC_SYSTEMS_VERSIONS;
CREATE sequence SEQ_INDICATORS_SYSTEMS;
CREATE sequence SEQ_INDICATORS_INSTANCES;
CREATE sequence SEQ_INDICATORS_VERSIONS;
CREATE sequence SEQ_INDICATORS;
CREATE sequence SEQ_I18NSTRS;
CREATE sequence SEQ_L10NSTRS;
CREATE sequence SEQ_DIMENSIONS;
CREATE sequence SEQ_ELEMENTS_LEVELS;
CREATE sequence SEQ_DATA_SOURCES;
CREATE sequence SEQ_DATA_SOURCES_VARIABLES;
