-- PENDIENTE ISTAC Lista de valores definitivos

-- GEOGRAPHIC GRANULARITIES

-- Countries
INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (SEQ_I18NSTRS.nextval, 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.nextval, 'Countries', 'en', SEQ_I18NSTRS.currval, 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.nextval, 'Países', 'es', SEQ_I18NSTRS.currval, 1);
INSERT INTO TB_LIS_GEOGR_GRANULARITIES (ID, CODE, UUID, TITLE_FK) VALUES (SEQ_GEOGR_GRANULARITIES.nextval, 'COUNTRIES', '1', SEQ_I18NSTRS.currval);

-- Municipalities
INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (SEQ_I18NSTRS.nextval, 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.nextval, 'Municipalities', 'en', SEQ_I18NSTRS.currval, 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.nextval, 'Municipios', 'es', SEQ_I18NSTRS.currval, 1);
INSERT INTO TB_LIS_GEOGR_GRANULARITIES (ID, CODE, UUID, TITLE_FK) VALUES (SEQ_GEOGR_GRANULARITIES.nextval, 'MUNICIPALITIES', '2', SEQ_I18NSTRS.currval);


-- GEOGRAPHIC VALUES

-- Spain
INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (SEQ_I18NSTRS.nextval, 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.nextval, 'Spain', 'en', SEQ_I18NSTRS.currval, 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.nextval, 'España', 'es', SEQ_I18NSTRS.currval, 1);
INSERT INTO TB_LIS_GEOGR_VALUES (ID, CODE, LATITUDE, LONGITUDE, UUID, TITLE_FK, GRANULARITY_FK) VALUES (SEQ_GEOGR_VALUES.nextval, 'ES', 20.0656233, -25.454564645, '1', null, 1);

-- Santa Cruz
INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (SEQ_I18NSTRS.nextval, 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.nextval, 'Santa Cruz de Tenerife', 'en', SEQ_I18NSTRS.currval, 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.nextval, 'Santa Cruz de Tenerife', 'es', SEQ_I18NSTRS.currval, 1);
INSERT INTO TB_LIS_GEOGR_VALUES (ID, CODE, LATITUDE, LONGITUDE, UUID, TITLE_FK, GRANULARITY_FK) VALUES (SEQ_GEOGR_VALUES.nextval, 'ES-SC', 22.232511, 32.254112, '2', SEQ_I18NSTRS.currval, 2);

-- France
INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (SEQ_I18NSTRS.nextval, 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.nextval, 'France', 'en', SEQ_I18NSTRS.currval, 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.nextval, 'Francia', 'es', SEQ_I18NSTRS.currval, 1);
INSERT INTO TB_LIS_GEOGR_VALUES (ID, CODE, LATITUDE, LONGITUDE, UUID, TITLE_FK, GRANULARITY_FK) VALUES (SEQ_GEOGR_VALUES.nextval, 'FR', 12.5656233, -15.46464565, '3', SEQ_I18NSTRS.currval, 1);