-- PENDIENTE ISTAC Lista de valores definitivos

-- GEOGRAPHIC GRANULARITIES

-- Countries
INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (SEQ_I18NSTRS.nextval, 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.nextval, 'Countries', 'en', SEQ_I18NSTRS.currval, 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.nextval, 'Países', 'es', SEQ_I18NSTRS.currval, 1);
INSERT INTO TB_LIS_GEOGR_GRANULARITIES (ID, CODE, UUID, TITLE_FK) values (SEQ_GEOGR_GRANULARITIES.nextval, 'COUNTRIES', '1', SEQ_I18NSTRS.currval);

	-- Country Geographical Values
	INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (Seq_I18nstrs.Nextval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, 'ESPAÑA', 'en', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, 'ESPAÑA', 'es', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LIS_GEOGR_VALUES (ID, CODE, LATITUDE, LONGITUDE, ORDER_IN_GRANULARITY, UUID, TITLE_FK, GRANULARITY_FK) values (SEQ_GEOGR_VALUES.NEXTVAL, 'ES', 20.0656233, -25.454564645, 1, '1', SEQ_I18NSTRS.currval, SEQ_GEOGR_GRANULARITIES.currval);

-- Regions
INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (SEQ_I18NSTRS.nextval, 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.nextval, 'Regions', 'en', SEQ_I18NSTRS.currval, 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.nextval, 'Comunidades autónomas', 'es', SEQ_I18NSTRS.currval, 1);
INSERT INTO TB_LIS_GEOGR_GRANULARITIES (ID, CODE, UUID, TITLE_FK) values (SEQ_GEOGR_GRANULARITIES.nextval, 'REGIONS', '2', SEQ_I18NSTRS.currval);


	-- Regions Geographicla Values
	INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (Seq_I18nstrs.Nextval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, ' ANDALUCÍA', 'en', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, ' ANDALUCÍA', 'es', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LIS_GEOGR_VALUES (ID, CODE, LATITUDE, LONGITUDE, ORDER_IN_GRANULARITY, UUID, TITLE_FK, GRANULARITY_FK) values (SEQ_GEOGR_VALUES.NEXTVAL, 'ES61', 20.0656233, -25.454564645, 1, '2', SEQ_I18NSTRS.currval, SEQ_GEOGR_GRANULARITIES.currval);
	
	
	INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (Seq_I18nstrs.Nextval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, ' ARAGÓN', 'en', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, ' ARAGÓN', 'es', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LIS_GEOGR_VALUES (ID, CODE, LATITUDE, LONGITUDE, ORDER_IN_GRANULARITY, UUID, TITLE_FK, GRANULARITY_FK) values (SEQ_GEOGR_VALUES.NEXTVAL, 'ES24', 20.0656233, -25.454564645, 2, '11', SEQ_I18NSTRS.currval, SEQ_GEOGR_GRANULARITIES.currval);
	
	
	INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (Seq_I18nstrs.Nextval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, ' ASTURIAS (PRINCIPADO DE)', 'en', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, ' ASTURIAS (PRINCIPADO DE)', 'es', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LIS_GEOGR_VALUES (ID, CODE, LATITUDE, LONGITUDE, ORDER_IN_GRANULARITY, UUID, TITLE_FK, GRANULARITY_FK) values (SEQ_GEOGR_VALUES.NEXTVAL, 'ES12', 20.0656233, -25.454564645, 3, '15', SEQ_I18NSTRS.currval, SEQ_GEOGR_GRANULARITIES.currval);
	
	
	INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (Seq_I18nstrs.Nextval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, ' BALEARS (ILLES)', 'en', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, ' BALEARS (ILLES)', 'es', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LIS_GEOGR_VALUES (ID, CODE, LATITUDE, LONGITUDE, ORDER_IN_GRANULARITY, UUID, TITLE_FK, GRANULARITY_FK) values (SEQ_GEOGR_VALUES.NEXTVAL, 'ES53', 20.0656233, -25.454564645, 4, '16', SEQ_I18NSTRS.currval, SEQ_GEOGR_GRANULARITIES.currval);
	
	
	INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (Seq_I18nstrs.Nextval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, ' CANARIAS', 'en', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, ' CANARIAS', 'es', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LIS_GEOGR_VALUES (ID, CODE, LATITUDE, LONGITUDE, ORDER_IN_GRANULARITY, UUID, TITLE_FK, GRANULARITY_FK) values (SEQ_GEOGR_VALUES.NEXTVAL, 'ES70', 20.0656233, -25.454564645, 5, '17', SEQ_I18NSTRS.currval, SEQ_GEOGR_GRANULARITIES.currval);
	
	
	INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (Seq_I18nstrs.Nextval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, ' CANTABRIA', 'en', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, ' CANTABRIA', 'es', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LIS_GEOGR_VALUES (ID, CODE, LATITUDE, LONGITUDE, ORDER_IN_GRANULARITY, UUID, TITLE_FK, GRANULARITY_FK) values (SEQ_GEOGR_VALUES.NEXTVAL, 'ES13', 20.0656233, -25.454564645, 6, '20', SEQ_I18NSTRS.currval, SEQ_GEOGR_GRANULARITIES.currval);
	
	
	INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (Seq_I18nstrs.Nextval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, ' CASTILLA Y LEÓN', 'en', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, ' CASTILLA Y LEÓN', 'es', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LIS_GEOGR_VALUES (ID, CODE, LATITUDE, LONGITUDE, ORDER_IN_GRANULARITY, UUID, TITLE_FK, GRANULARITY_FK) values (SEQ_GEOGR_VALUES.NEXTVAL, 'ES41', 20.0656233, -25.454564645, 7, '21', SEQ_I18NSTRS.currval, SEQ_GEOGR_GRANULARITIES.currval);
	
	
	INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (Seq_I18nstrs.Nextval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, ' CASTILLA-LA MANCHA', 'en', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, ' CASTILLA-LA MANCHA', 'es', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LIS_GEOGR_VALUES (ID, CODE, LATITUDE, LONGITUDE, ORDER_IN_GRANULARITY, UUID, TITLE_FK, GRANULARITY_FK) values (SEQ_GEOGR_VALUES.NEXTVAL, 'ES42', 20.0656233, -25.454564645, 8, '31', SEQ_I18NSTRS.currval, SEQ_GEOGR_GRANULARITIES.currval);
	
	
	INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (Seq_I18nstrs.Nextval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, ' CATALUÑA', 'en', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, ' CATALUÑA', 'es', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LIS_GEOGR_VALUES (ID, CODE, LATITUDE, LONGITUDE, ORDER_IN_GRANULARITY, UUID, TITLE_FK, GRANULARITY_FK) values (SEQ_GEOGR_VALUES.NEXTVAL, 'ES51', 20.0656233, -25.454564645, 9, '37', SEQ_I18NSTRS.currval, SEQ_GEOGR_GRANULARITIES.currval);
	
	
	INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (Seq_I18nstrs.Nextval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, ' COMUNITAT VALENCIANA', 'en', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, ' COMUNITAT VALENCIANA', 'es', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LIS_GEOGR_VALUES (ID, CODE, LATITUDE, LONGITUDE, ORDER_IN_GRANULARITY, UUID, TITLE_FK, GRANULARITY_FK) values (SEQ_GEOGR_VALUES.NEXTVAL, 'ES52', 20.0656233, -25.454564645, 10, '42', SEQ_I18NSTRS.currval, SEQ_GEOGR_GRANULARITIES.currval);
	
	
	INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (Seq_I18nstrs.Nextval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, ' EXTREMADURA', 'en', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, ' EXTREMADURA', 'es', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LIS_GEOGR_VALUES (ID, CODE, LATITUDE, LONGITUDE, ORDER_IN_GRANULARITY, UUID, TITLE_FK, GRANULARITY_FK) values (SEQ_GEOGR_VALUES.NEXTVAL, 'ES43', 20.0656233, -25.454564645, 11, '46', SEQ_I18NSTRS.currval, SEQ_GEOGR_GRANULARITIES.currval);
	
	
	INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (Seq_I18nstrs.Nextval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, ' GALICIA', 'en', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, ' GALICIA', 'es', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LIS_GEOGR_VALUES (ID, CODE, LATITUDE, LONGITUDE, ORDER_IN_GRANULARITY, UUID, TITLE_FK, GRANULARITY_FK) values (SEQ_GEOGR_VALUES.NEXTVAL, 'ES11', 20.0656233, -25.454564645, 12, '49', SEQ_I18NSTRS.currval, SEQ_GEOGR_GRANULARITIES.currval);
	
	
	INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (Seq_I18nstrs.Nextval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, ' MADRID (COMUNIDAD DE)', 'en', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, ' MADRID (COMUNIDAD DE)', 'es', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LIS_GEOGR_VALUES (ID, CODE, LATITUDE, LONGITUDE, ORDER_IN_GRANULARITY, UUID, TITLE_FK, GRANULARITY_FK) values (SEQ_GEOGR_VALUES.NEXTVAL, 'ES30', 20.0656233, -25.454564645, 13, '54', SEQ_I18NSTRS.currval, SEQ_GEOGR_GRANULARITIES.currval);
	
	
	INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (Seq_I18nstrs.Nextval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, ' MURCIA (REGIÓN DE)', 'en', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, ' MURCIA (REGIÓN DE)', 'es', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LIS_GEOGR_VALUES (ID, CODE, LATITUDE, LONGITUDE, ORDER_IN_GRANULARITY, UUID, TITLE_FK, GRANULARITY_FK) values (SEQ_GEOGR_VALUES.NEXTVAL, 'ES62', 20.0656233, -25.454564645, 14, '55', SEQ_I18NSTRS.currval, SEQ_GEOGR_GRANULARITIES.currval);
	
	
	INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (Seq_I18nstrs.Nextval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, ' NAVARRA (COMUNIDAD FORAL DE)', 'en', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, ' NAVARRA (COMUNIDAD FORAL DE)', 'es', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LIS_GEOGR_VALUES (ID, CODE, LATITUDE, LONGITUDE, ORDER_IN_GRANULARITY, UUID, TITLE_FK, GRANULARITY_FK) values (SEQ_GEOGR_VALUES.NEXTVAL, 'ES22', 20.0656233, -25.454564645, 15, '56', SEQ_I18NSTRS.currval, SEQ_GEOGR_GRANULARITIES.currval);
	
	
	INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (Seq_I18nstrs.Nextval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, ' PAÍS VASCO', 'en', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, ' PAÍS VASCO', 'es', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LIS_GEOGR_VALUES (ID, CODE, LATITUDE, LONGITUDE, ORDER_IN_GRANULARITY, UUID, TITLE_FK, GRANULARITY_FK) values (SEQ_GEOGR_VALUES.NEXTVAL, 'ES21', 20.0656233, -25.454564645, 16, '57', SEQ_I18NSTRS.currval, SEQ_GEOGR_GRANULARITIES.currval);
	
	
	INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (Seq_I18nstrs.Nextval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, ' RIOJA (LA)', 'en', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, ' RIOJA (LA)', 'es', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LIS_GEOGR_VALUES (ID, CODE, LATITUDE, LONGITUDE, ORDER_IN_GRANULARITY, UUID, TITLE_FK, GRANULARITY_FK) values (SEQ_GEOGR_VALUES.NEXTVAL, 'ES23', 20.0656233, -25.454564645, 17, '61', SEQ_I18NSTRS.currval, SEQ_GEOGR_GRANULARITIES.currval);
	
	
	INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (Seq_I18nstrs.Nextval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, ' CEUTA', 'en', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, ' CEUTA', 'es', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LIS_GEOGR_VALUES (ID, CODE, LATITUDE, LONGITUDE, ORDER_IN_GRANULARITY, UUID, TITLE_FK, GRANULARITY_FK) values (SEQ_GEOGR_VALUES.NEXTVAL, 'ES63', 20.0656233, -25.454564645, 18, '62', SEQ_I18NSTRS.currval, SEQ_GEOGR_GRANULARITIES.currval);
	
	
	INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (Seq_I18nstrs.Nextval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, ' MELILLA', 'en', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, ' MELILLA', 'es', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LIS_GEOGR_VALUES (ID, CODE, LATITUDE, LONGITUDE, ORDER_IN_GRANULARITY, UUID, TITLE_FK, GRANULARITY_FK) values (SEQ_GEOGR_VALUES.NEXTVAL, 'ES64', 20.0656233, -25.454564645, 19, '63', SEQ_I18NSTRS.currval, SEQ_GEOGR_GRANULARITIES.currval);


-- Provinces
INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (SEQ_I18NSTRS.nextval, 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.nextval, 'Provinces', 'en', SEQ_I18NSTRS.currval, 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.nextval, 'Provincias', 'es', SEQ_I18NSTRS.currval, 1);
INSERT INTO TB_LIS_GEOGR_GRANULARITIES (ID, CODE, UUID, TITLE_FK) values (SEQ_GEOGR_GRANULARITIES.nextval, 'PROVINCES', '3', SEQ_I18NSTRS.currval);


	-- Province Geographical values
	
	INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (Seq_I18nstrs.Nextval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Almería', 'en', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Almería', 'es', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LIS_GEOGR_VALUES (ID, CODE, LATITUDE, LONGITUDE, ORDER_IN_GRANULARITY, UUID, TITLE_FK, GRANULARITY_FK) values (SEQ_GEOGR_VALUES.NEXTVAL, 'ES611', 20.0656233, -25.454564645, 1, '3', SEQ_I18NSTRS.currval, SEQ_GEOGR_GRANULARITIES.currval);
	
	
	INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (Seq_I18nstrs.Nextval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Cádiz', 'en', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Cádiz', 'es', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LIS_GEOGR_VALUES (ID, CODE, LATITUDE, LONGITUDE, ORDER_IN_GRANULARITY, UUID, TITLE_FK, GRANULARITY_FK) values (SEQ_GEOGR_VALUES.NEXTVAL, 'ES612', 20.0656233, -25.454564645, 2, '4', SEQ_I18NSTRS.currval, SEQ_GEOGR_GRANULARITIES.currval);
	
	
	INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (Seq_I18nstrs.Nextval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Córdoba', 'en', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Córdoba', 'es', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LIS_GEOGR_VALUES (ID, CODE, LATITUDE, LONGITUDE, ORDER_IN_GRANULARITY, UUID, TITLE_FK, GRANULARITY_FK) values (SEQ_GEOGR_VALUES.NEXTVAL, 'ES613', 20.0656233, -25.454564645, 3, '5', SEQ_I18NSTRS.currval, SEQ_GEOGR_GRANULARITIES.currval);
	
	
	INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (Seq_I18nstrs.Nextval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Granada', 'en', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Granada', 'es', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LIS_GEOGR_VALUES (ID, CODE, LATITUDE, LONGITUDE, ORDER_IN_GRANULARITY, UUID, TITLE_FK, GRANULARITY_FK) values (SEQ_GEOGR_VALUES.NEXTVAL, 'ES614', 20.0656233, -25.454564645, 4, '6', SEQ_I18NSTRS.currval, SEQ_GEOGR_GRANULARITIES.currval);
	
	
	INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (Seq_I18nstrs.Nextval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Huelva', 'en', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Huelva', 'es', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LIS_GEOGR_VALUES (ID, CODE, LATITUDE, LONGITUDE, ORDER_IN_GRANULARITY, UUID, TITLE_FK, GRANULARITY_FK) values (SEQ_GEOGR_VALUES.NEXTVAL, 'ES615', 20.0656233, -25.454564645, 5, '7', SEQ_I18NSTRS.currval, SEQ_GEOGR_GRANULARITIES.currval);
	
	
	INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (Seq_I18nstrs.Nextval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Jaén', 'en', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Jaén', 'es', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LIS_GEOGR_VALUES (ID, CODE, LATITUDE, LONGITUDE, ORDER_IN_GRANULARITY, UUID, TITLE_FK, GRANULARITY_FK) values (SEQ_GEOGR_VALUES.NEXTVAL, 'ES616', 20.0656233, -25.454564645, 6, '8', SEQ_I18NSTRS.currval, SEQ_GEOGR_GRANULARITIES.currval);
	
	
	INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (Seq_I18nstrs.Nextval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Málaga', 'en', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Málaga', 'es', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LIS_GEOGR_VALUES (ID, CODE, LATITUDE, LONGITUDE, ORDER_IN_GRANULARITY, UUID, TITLE_FK, GRANULARITY_FK) values (SEQ_GEOGR_VALUES.NEXTVAL, 'ES617', 20.0656233, -25.454564645, 7, '9', SEQ_I18NSTRS.currval, SEQ_GEOGR_GRANULARITIES.currval);
	
	
	INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (Seq_I18nstrs.Nextval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Sevilla', 'en', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Sevilla', 'es', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LIS_GEOGR_VALUES (ID, CODE, LATITUDE, LONGITUDE, ORDER_IN_GRANULARITY, UUID, TITLE_FK, GRANULARITY_FK) values (SEQ_GEOGR_VALUES.NEXTVAL, 'ES618', 20.0656233, -25.454564645, 8, '10', SEQ_I18NSTRS.currval, SEQ_GEOGR_GRANULARITIES.currval);
	
	
	INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (Seq_I18nstrs.Nextval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Huesca', 'en', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Huesca', 'es', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LIS_GEOGR_VALUES (ID, CODE, LATITUDE, LONGITUDE, ORDER_IN_GRANULARITY, UUID, TITLE_FK, GRANULARITY_FK) values (SEQ_GEOGR_VALUES.NEXTVAL, 'ES241', 20.0656233, -25.454564645, 9, '12', SEQ_I18NSTRS.currval, SEQ_GEOGR_GRANULARITIES.currval);
	
	
	INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (Seq_I18nstrs.Nextval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Teruel', 'en', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Teruel', 'es', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LIS_GEOGR_VALUES (ID, CODE, LATITUDE, LONGITUDE, ORDER_IN_GRANULARITY, UUID, TITLE_FK, GRANULARITY_FK) values (SEQ_GEOGR_VALUES.NEXTVAL, 'ES242', 20.0656233, -25.454564645, 10, '13', SEQ_I18NSTRS.currval, SEQ_GEOGR_GRANULARITIES.currval);
	
	
	INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (Seq_I18nstrs.Nextval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Zaragoza', 'en', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Zaragoza', 'es', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LIS_GEOGR_VALUES (ID, CODE, LATITUDE, LONGITUDE, ORDER_IN_GRANULARITY, UUID, TITLE_FK, GRANULARITY_FK) values (SEQ_GEOGR_VALUES.NEXTVAL, 'ES243', 20.0656233, -25.454564645, 11, '14', SEQ_I18NSTRS.currval, SEQ_GEOGR_GRANULARITIES.currval);
	
	
	INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (Seq_I18nstrs.Nextval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Palmas (Las)', 'en', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Palmas (Las)', 'es', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LIS_GEOGR_VALUES (ID, CODE, LATITUDE, LONGITUDE, ORDER_IN_GRANULARITY, UUID, TITLE_FK, GRANULARITY_FK) values (SEQ_GEOGR_VALUES.NEXTVAL, 'ES701', 20.0656233, -25.454564645, 12, '18', SEQ_I18NSTRS.currval, SEQ_GEOGR_GRANULARITIES.currval);
	
	
	INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (Seq_I18nstrs.Nextval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Santa Cruz de Tenerife', 'en', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Santa Cruz de Tenerife', 'es', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LIS_GEOGR_VALUES (ID, CODE, LATITUDE, LONGITUDE, ORDER_IN_GRANULARITY, UUID, TITLE_FK, GRANULARITY_FK) values (SEQ_GEOGR_VALUES.NEXTVAL, 'ES702', 20.0656233, -25.454564645, 13, '19', SEQ_I18NSTRS.currval, SEQ_GEOGR_GRANULARITIES.currval);
	
	
	INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (Seq_I18nstrs.Nextval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Ávila', 'en', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Ávila', 'es', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LIS_GEOGR_VALUES (ID, CODE, LATITUDE, LONGITUDE, ORDER_IN_GRANULARITY, UUID, TITLE_FK, GRANULARITY_FK) values (SEQ_GEOGR_VALUES.NEXTVAL, 'ES411', 20.0656233, -25.454564645, 14, '22', SEQ_I18NSTRS.currval, SEQ_GEOGR_GRANULARITIES.currval);
	
	
	INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (Seq_I18nstrs.Nextval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Burgos', 'en', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Burgos', 'es', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LIS_GEOGR_VALUES (ID, CODE, LATITUDE, LONGITUDE, ORDER_IN_GRANULARITY, UUID, TITLE_FK, GRANULARITY_FK) values (SEQ_GEOGR_VALUES.NEXTVAL, 'ES412', 20.0656233, -25.454564645, 15, '23', SEQ_I18NSTRS.currval, SEQ_GEOGR_GRANULARITIES.currval);
	
	
	INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (Seq_I18nstrs.Nextval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  León', 'en', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  León', 'es', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LIS_GEOGR_VALUES (ID, CODE, LATITUDE, LONGITUDE, ORDER_IN_GRANULARITY, UUID, TITLE_FK, GRANULARITY_FK) values (SEQ_GEOGR_VALUES.NEXTVAL, 'ES413', 20.0656233, -25.454564645, 16, '24', SEQ_I18NSTRS.currval, SEQ_GEOGR_GRANULARITIES.currval);
	
	
	INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (Seq_I18nstrs.Nextval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Palencia', 'en', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Palencia', 'es', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LIS_GEOGR_VALUES (ID, CODE, LATITUDE, LONGITUDE, ORDER_IN_GRANULARITY, UUID, TITLE_FK, GRANULARITY_FK) values (SEQ_GEOGR_VALUES.NEXTVAL, 'ES414', 20.0656233, -25.454564645, 17, '25', SEQ_I18NSTRS.currval, SEQ_GEOGR_GRANULARITIES.currval);
	
	
	INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (Seq_I18nstrs.Nextval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Salamanca', 'en', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Salamanca', 'es', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LIS_GEOGR_VALUES (ID, CODE, LATITUDE, LONGITUDE, ORDER_IN_GRANULARITY, UUID, TITLE_FK, GRANULARITY_FK) values (SEQ_GEOGR_VALUES.NEXTVAL, 'ES415', 20.0656233, -25.454564645, 18, '26', SEQ_I18NSTRS.currval, SEQ_GEOGR_GRANULARITIES.currval);
	
	
	INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (Seq_I18nstrs.Nextval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Segovia', 'en', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Segovia', 'es', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LIS_GEOGR_VALUES (ID, CODE, LATITUDE, LONGITUDE, ORDER_IN_GRANULARITY, UUID, TITLE_FK, GRANULARITY_FK) values (SEQ_GEOGR_VALUES.NEXTVAL, 'ES416', 20.0656233, -25.454564645, 19, '27', SEQ_I18NSTRS.currval, SEQ_GEOGR_GRANULARITIES.currval);
	
	
	INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (Seq_I18nstrs.Nextval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Soria', 'en', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Soria', 'es', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LIS_GEOGR_VALUES (ID, CODE, LATITUDE, LONGITUDE, ORDER_IN_GRANULARITY, UUID, TITLE_FK, GRANULARITY_FK) values (SEQ_GEOGR_VALUES.NEXTVAL, 'ES417', 20.0656233, -25.454564645, 20, '28', SEQ_I18NSTRS.currval, SEQ_GEOGR_GRANULARITIES.currval);
	
	
	INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (Seq_I18nstrs.Nextval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Valladolid', 'en', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Valladolid', 'es', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LIS_GEOGR_VALUES (ID, CODE, LATITUDE, LONGITUDE, ORDER_IN_GRANULARITY, UUID, TITLE_FK, GRANULARITY_FK) values (SEQ_GEOGR_VALUES.NEXTVAL, 'ES418', 20.0656233, -25.454564645, 21, '29', SEQ_I18NSTRS.currval, SEQ_GEOGR_GRANULARITIES.currval);
	
	
	INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (Seq_I18nstrs.Nextval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Zamora', 'en', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Zamora', 'es', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LIS_GEOGR_VALUES (ID, CODE, LATITUDE, LONGITUDE, ORDER_IN_GRANULARITY, UUID, TITLE_FK, GRANULARITY_FK) values (SEQ_GEOGR_VALUES.NEXTVAL, 'ES419', 20.0656233, -25.454564645, 22, '30', SEQ_I18NSTRS.currval, SEQ_GEOGR_GRANULARITIES.currval);
	
	
	INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (Seq_I18nstrs.Nextval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Albacete', 'en', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Albacete', 'es', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LIS_GEOGR_VALUES (ID, CODE, LATITUDE, LONGITUDE, ORDER_IN_GRANULARITY, UUID, TITLE_FK, GRANULARITY_FK) values (SEQ_GEOGR_VALUES.NEXTVAL, 'ES421', 20.0656233, -25.454564645, 23, '32', SEQ_I18NSTRS.currval, SEQ_GEOGR_GRANULARITIES.currval);
	
	
	INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (Seq_I18nstrs.Nextval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Ciudad Real', 'en', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Ciudad Real', 'es', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LIS_GEOGR_VALUES (ID, CODE, LATITUDE, LONGITUDE, ORDER_IN_GRANULARITY, UUID, TITLE_FK, GRANULARITY_FK) values (SEQ_GEOGR_VALUES.NEXTVAL, 'ES422', 20.0656233, -25.454564645, 24, '33', SEQ_I18NSTRS.currval, SEQ_GEOGR_GRANULARITIES.currval);
	
	
	INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (Seq_I18nstrs.Nextval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Cuenca', 'en', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Cuenca', 'es', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LIS_GEOGR_VALUES (ID, CODE, LATITUDE, LONGITUDE, ORDER_IN_GRANULARITY, UUID, TITLE_FK, GRANULARITY_FK) values (SEQ_GEOGR_VALUES.NEXTVAL, 'ES423', 20.0656233, -25.454564645, 25, '34', SEQ_I18NSTRS.currval, SEQ_GEOGR_GRANULARITIES.currval);
	
	
	INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (Seq_I18nstrs.Nextval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Guadalajara', 'en', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Guadalajara', 'es', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LIS_GEOGR_VALUES (ID, CODE, LATITUDE, LONGITUDE, ORDER_IN_GRANULARITY, UUID, TITLE_FK, GRANULARITY_FK) values (SEQ_GEOGR_VALUES.NEXTVAL, 'ES424', 20.0656233, -25.454564645, 26, '35', SEQ_I18NSTRS.currval, SEQ_GEOGR_GRANULARITIES.currval);
	
	
	INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (Seq_I18nstrs.Nextval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Toledo', 'en', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Toledo', 'es', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LIS_GEOGR_VALUES (ID, CODE, LATITUDE, LONGITUDE, ORDER_IN_GRANULARITY, UUID, TITLE_FK, GRANULARITY_FK) values (SEQ_GEOGR_VALUES.NEXTVAL, 'ES425', 20.0656233, -25.454564645, 27, '36', SEQ_I18NSTRS.currval, SEQ_GEOGR_GRANULARITIES.currval);
	
	
	INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (Seq_I18nstrs.Nextval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Barcelona', 'en', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Barcelona', 'es', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LIS_GEOGR_VALUES (ID, CODE, LATITUDE, LONGITUDE, ORDER_IN_GRANULARITY, UUID, TITLE_FK, GRANULARITY_FK) values (SEQ_GEOGR_VALUES.NEXTVAL, 'ES511', 20.0656233, -25.454564645, 28, '38', SEQ_I18NSTRS.currval, SEQ_GEOGR_GRANULARITIES.currval);
	
	
	INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (Seq_I18nstrs.Nextval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Girona', 'en', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Girona', 'es', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LIS_GEOGR_VALUES (ID, CODE, LATITUDE, LONGITUDE, ORDER_IN_GRANULARITY, UUID, TITLE_FK, GRANULARITY_FK) values (SEQ_GEOGR_VALUES.NEXTVAL, 'ES512', 20.0656233, -25.454564645, 29, '39', SEQ_I18NSTRS.currval, SEQ_GEOGR_GRANULARITIES.currval);
	
	
	INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (Seq_I18nstrs.Nextval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Lleida', 'en', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Lleida', 'es', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LIS_GEOGR_VALUES (ID, CODE, LATITUDE, LONGITUDE, ORDER_IN_GRANULARITY, UUID, TITLE_FK, GRANULARITY_FK) values (SEQ_GEOGR_VALUES.NEXTVAL, 'ES513', 20.0656233, -25.454564645, 30, '40', SEQ_I18NSTRS.currval, SEQ_GEOGR_GRANULARITIES.currval);
	
	
	INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (Seq_I18nstrs.Nextval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Tarragona', 'en', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Tarragona', 'es', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LIS_GEOGR_VALUES (ID, CODE, LATITUDE, LONGITUDE, ORDER_IN_GRANULARITY, UUID, TITLE_FK, GRANULARITY_FK) values (SEQ_GEOGR_VALUES.NEXTVAL, 'ES514', 20.0656233, -25.454564645, 31, '41', SEQ_I18NSTRS.currval, SEQ_GEOGR_GRANULARITIES.currval);
	
	
	INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (Seq_I18nstrs.Nextval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Alicante/Alacant', 'en', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Alicante/Alacant', 'es', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LIS_GEOGR_VALUES (ID, CODE, LATITUDE, LONGITUDE, ORDER_IN_GRANULARITY, UUID, TITLE_FK, GRANULARITY_FK) values (SEQ_GEOGR_VALUES.NEXTVAL, 'ES521', 20.0656233, -25.454564645, 32, '43', SEQ_I18NSTRS.currval, SEQ_GEOGR_GRANULARITIES.currval);
	
	
	INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (Seq_I18nstrs.Nextval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Castellón/Castelló', 'en', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Castellón/Castelló', 'es', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LIS_GEOGR_VALUES (ID, CODE, LATITUDE, LONGITUDE, ORDER_IN_GRANULARITY, UUID, TITLE_FK, GRANULARITY_FK) values (SEQ_GEOGR_VALUES.NEXTVAL, 'ES522', 20.0656233, -25.454564645, 33, '44', SEQ_I18NSTRS.currval, SEQ_GEOGR_GRANULARITIES.currval);
	
	
	INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (Seq_I18nstrs.Nextval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Valencia/València', 'en', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Valencia/València', 'es', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LIS_GEOGR_VALUES (ID, CODE, LATITUDE, LONGITUDE, ORDER_IN_GRANULARITY, UUID, TITLE_FK, GRANULARITY_FK) values (SEQ_GEOGR_VALUES.NEXTVAL, 'ES523', 20.0656233, -25.454564645, 34, '45', SEQ_I18NSTRS.currval, SEQ_GEOGR_GRANULARITIES.currval);
	
	
	INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (Seq_I18nstrs.Nextval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Badajoz', 'en', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Badajoz', 'es', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LIS_GEOGR_VALUES (ID, CODE, LATITUDE, LONGITUDE, ORDER_IN_GRANULARITY, UUID, TITLE_FK, GRANULARITY_FK) values (SEQ_GEOGR_VALUES.NEXTVAL, 'ES431', 20.0656233, -25.454564645, 35, '47', SEQ_I18NSTRS.currval, SEQ_GEOGR_GRANULARITIES.currval);
	
	
	INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (Seq_I18nstrs.Nextval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Cáceres', 'en', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Cáceres', 'es', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LIS_GEOGR_VALUES (ID, CODE, LATITUDE, LONGITUDE, ORDER_IN_GRANULARITY, UUID, TITLE_FK, GRANULARITY_FK) values (SEQ_GEOGR_VALUES.NEXTVAL, 'ES432', 20.0656233, -25.454564645, 36, '48', SEQ_I18NSTRS.currval, SEQ_GEOGR_GRANULARITIES.currval);
	
	
	INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (Seq_I18nstrs.Nextval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Coruña (A)', 'en', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Coruña (A)', 'es', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LIS_GEOGR_VALUES (ID, CODE, LATITUDE, LONGITUDE, ORDER_IN_GRANULARITY, UUID, TITLE_FK, GRANULARITY_FK) values (SEQ_GEOGR_VALUES.NEXTVAL, 'ES111', 20.0656233, -25.454564645, 37, '50', SEQ_I18NSTRS.currval, SEQ_GEOGR_GRANULARITIES.currval);
	
	
	INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (Seq_I18nstrs.Nextval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Lugo', 'en', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Lugo', 'es', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LIS_GEOGR_VALUES (ID, CODE, LATITUDE, LONGITUDE, ORDER_IN_GRANULARITY, UUID, TITLE_FK, GRANULARITY_FK) values (SEQ_GEOGR_VALUES.NEXTVAL, 'ES112', 20.0656233, -25.454564645, 38, '51', SEQ_I18NSTRS.currval, SEQ_GEOGR_GRANULARITIES.currval);
	
	
	INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (Seq_I18nstrs.Nextval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Ourense', 'en', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Ourense', 'es', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LIS_GEOGR_VALUES (ID, CODE, LATITUDE, LONGITUDE, ORDER_IN_GRANULARITY, UUID, TITLE_FK, GRANULARITY_FK) values (SEQ_GEOGR_VALUES.NEXTVAL, 'ES113', 20.0656233, -25.454564645, 39, '52', SEQ_I18NSTRS.currval, SEQ_GEOGR_GRANULARITIES.currval);
	
	
	INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (Seq_I18nstrs.Nextval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Pontevedra', 'en', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Pontevedra', 'es', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LIS_GEOGR_VALUES (ID, CODE, LATITUDE, LONGITUDE, ORDER_IN_GRANULARITY, UUID, TITLE_FK, GRANULARITY_FK) values (SEQ_GEOGR_VALUES.NEXTVAL, 'ES114', 20.0656233, -25.454564645, 40, '53', SEQ_I18NSTRS.currval, SEQ_GEOGR_GRANULARITIES.currval);
	
	
	INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (Seq_I18nstrs.Nextval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Álava', 'en', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Álava', 'es', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LIS_GEOGR_VALUES (ID, CODE, LATITUDE, LONGITUDE, ORDER_IN_GRANULARITY, UUID, TITLE_FK, GRANULARITY_FK) values (SEQ_GEOGR_VALUES.NEXTVAL, 'ES211', 20.0656233, -25.454564645, 41, '58', SEQ_I18NSTRS.currval, SEQ_GEOGR_GRANULARITIES.currval);
	
	
	INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (Seq_I18nstrs.Nextval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Guipúzcoa', 'en', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Guipúzcoa', 'es', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LIS_GEOGR_VALUES (ID, CODE, LATITUDE, LONGITUDE, ORDER_IN_GRANULARITY, UUID, TITLE_FK, GRANULARITY_FK) values (SEQ_GEOGR_VALUES.NEXTVAL, 'ES212', 20.0656233, -25.454564645, 42, '59', SEQ_I18NSTRS.currval, SEQ_GEOGR_GRANULARITIES.currval);
	
	
	INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (Seq_I18nstrs.Nextval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Vizcaya', 'en', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.NEXTVAL, '  Vizcaya', 'es', Seq_I18nstrs.Currval, 1);
	INSERT INTO TB_LIS_GEOGR_VALUES (ID, CODE, LATITUDE, LONGITUDE, ORDER_IN_GRANULARITY, UUID, TITLE_FK, GRANULARITY_FK) values (SEQ_GEOGR_VALUES.NEXTVAL, 'ES213', 20.0656233, -25.454564645, 43, '60', SEQ_I18NSTRS.currval, SEQ_GEOGR_GRANULARITIES.currval);


-- Municipalities
INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (SEQ_I18NSTRS.nextval, 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.nextval, 'Municipalities', 'en', SEQ_I18NSTRS.currval, 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.nextval, 'Municipios', 'es', SEQ_I18NSTRS.currval, 1);
INSERT INTO TB_LIS_GEOGR_GRANULARITIES (ID, CODE, UUID, TITLE_FK) values (SEQ_GEOGR_GRANULARITIES.nextval, 'MUNICIPALITIES', '4', SEQ_I18NSTRS.currval);
