-- Example values

-- SUBJECTS
INSERT INTO TV_CATALOGO_OPERACION_ESTADIST (ID_CATALOGO, DESCRIPCION) VALUES ('EDUCACION', 'Educación');
INSERT INTO TV_CATALOGO_OPERACION_ESTADIST (ID_CATALOGO, DESCRIPCION) VALUES ('POLITICA_ECONOMICA', 'Política económica');
INSERT INTO TV_CATALOGO_OPERACION_ESTADIST (ID_CATALOGO, DESCRIPCION) VALUES ('SALUD', 'Salud');
INSERT INTO TV_CATALOGO_OPERACION_ESTADIST (ID_CATALOGO, DESCRIPCION) VALUES ('MEDIO_AMBIENTE', 'Medio ambiente');
