
    
-- ###########################################
-- # Drop
-- ###########################################
-- Drop index
  
  


-- Drop many to many relations
    
-- Drop normal entities
    
DROP TABLE TBL_LOCALISED_STRINGS CASCADE CONSTRAINTS PURGE;

DROP TABLE TBL_DIMENSIONS CASCADE CONSTRAINTS PURGE;

DROP TABLE TBL_INDIC_SYSTEMS_VERSIONS CASCADE CONSTRAINTS PURGE;

DROP TABLE TBL_INDICATORS_SYSTEMS CASCADE CONSTRAINTS PURGE;

DROP TABLE TBL_DATA_SOURCES CASCADE CONSTRAINTS PURGE;

DROP TABLE TBL_INDICATOR_VERSIONS CASCADE CONSTRAINTS PURGE;

DROP TABLE TBL_INDICATORS CASCADE CONSTRAINTS PURGE;

DROP TABLE TBL_INTERNATIONAL_STRINGS CASCADE CONSTRAINTS PURGE;
    