   	
DROP TABLE TBL_LOCALISED_STRINGS CASCADE CONSTRAINTS PURGE;


    	
DROP TABLE TBL_DIMENSIONS CASCADE CONSTRAINTS PURGE;

    	
DROP TABLE TBL_ELEMENTS_LEVELS CASCADE CONSTRAINTS PURGE;

    	
DROP TABLE TBL_INDIC_SYSTEMS_VERSIONS CASCADE CONSTRAINTS PURGE;

    	
DROP TABLE TBL_INDICATORS_SYSTEMS CASCADE CONSTRAINTS PURGE;

    	
DROP TABLE TBL_INDICATORS_INSTANCES CASCADE CONSTRAINTS PURGE;

    	
DROP TABLE TBL_DATA_SOURCES_VARIABLES CASCADE CONSTRAINTS PURGE;

    	
DROP TABLE TBL_DATA_SOURCES CASCADE CONSTRAINTS PURGE;

    	
DROP TABLE TBL_RATES_DERIVATIONS CASCADE CONSTRAINTS PURGE;

    	
DROP TABLE TBL_INDICATORS_VERSIONS CASCADE CONSTRAINTS PURGE;

    	
DROP TABLE TBL_QUANTITIES CASCADE CONSTRAINTS PURGE;

    	
DROP TABLE LIS_GEOGR_VALUES CASCADE CONSTRAINTS PURGE;

    	
DROP TABLE LIS_GEOGR_GRANULARITIES CASCADE CONSTRAINTS PURGE;

    	
DROP TABLE LIS_QUANTITIES_UNITS CASCADE CONSTRAINTS PURGE;

    	
DROP TABLE TBL_INDICATORS CASCADE CONSTRAINTS PURGE;

    	
DROP TABLE TBL_INTERNATIONAL_STRINGS CASCADE CONSTRAINTS PURGE;

DROP sequence SEQ_INDIC_SYSTEMS_VERSIONS;
DROP sequence SEQ_INDICATORS_SYSTEMS;
DROP sequence SEQ_INDICATORS_INSTANCES;
DROP sequence SEQ_INDICATORS_VERSIONS;
DROP sequence SEQ_INDICATORS;
DROP sequence SEQ_I18NSTRS;
DROP sequence SEQ_L10NSTRS;
DROP sequence SEQ_DIMENSIONS;
DROP sequence SEQ_ELEMENTS_LEVELS;
DROP sequence SEQ_DATA_SOURCES;
DROP sequence SEQ_DATA_SOURCES_VARIABLES;
DROP sequence SEQ_QUANTITIES;
DROP sequence SEQ_QUANTITIES_UNITS;
DROP sequence SEQ_RATES_DERIVATIONS;
DROP sequence SEQ_GEOGR_VALUES;
DROP sequence SEQ_GEOGR_GRANULARITIES;