ALTER TABLE TB_LOCALISED_STRINGS ADD CONSTRAINT LOCALE_INTERNATIONAL UNIQUE(LOCALE, INTERNATIONAL_STRING_FK) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE TB_INDICATORS_SYSTEMS ADD CONSTRAINT INDICATORS_SYSTEMS_CODE UNIQUE(CODE);
ALTER TABLE TB_INDICATORS ADD CONSTRAINT INDICATORS_CODE UNIQUE(CODE);
ALTER TABLE TB_INDICATORS ADD CONSTRAINT INDICATORS_CODE_VIEW UNIQUE(VIEW_CODE);
ALTER TABLE TB_INDICATORS_VERSIONS ADD CONSTRAINT INDICATORS_DATA_REP_ID UNIQUE(DATA_REPOSITORY_ID);
ALTER TABLE TB_INDICATORS_VERSIONS ADD CONSTRAINT INDICATORS_DATA_REP_TN UNIQUE(DATA_REPOSITORY_TABLE_NAME);
ALTER TABLE TB_ELEMENTS_LEVELS ADD CONSTRAINT ORDERS_UNIQUE UNIQUE(ORDER_IN_LEVEL, IND_SYSTEM_VERSION_FIRST_FK, PARENT_FK) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE TB_LIS_GEOGR_VALUES ADD CONSTRAINT GEOGR_VALUES_CODE UNIQUE(CODE);
ALTER TABLE TB_LIS_GEOGR_VALUES ADD CONSTRAINT GEOGR_VALUES_ORDER UNIQUE(GLOBAL_ORDER);
ALTER TABLE TB_LIS_GEOGR_GRANULARITIES ADD CONSTRAINT GEOGR_GRANULARITIES_CODE UNIQUE(CODE);
ALTER TABLE TB_LIS_UNITS_MULTIPLIERS ADD CONSTRAINT UNIT_MULTIPLIER UNIQUE(UNIT_MULTIPLIER);
ALTER TABLE TB_TRANSLATIONS ADD CONSTRAINT TRANSLATIONS_CODE UNIQUE(CODE);

ALTER TABLE TB_IND_VERSION_GEO_COV DROP CONSTRAINT FK_TB_IND_VERSION_GEO_COV_IN03;
ALTER TABLE TB_IND_VERSION_GEO_COV ADD CONSTRAINT FK_TB_IND_VERSION_GEO_COV_IN03 FOREIGN KEY (INDICATOR_VERSION_FK) REFERENCES TB_INDICATORS_VERSIONS (ID) ON DELETE CASCADE;
	
ALTER TABLE TB_IND_VERSION_TIME_COV DROP CONSTRAINT FK_TB_IND_VERSION_TIME_COV_I71;
ALTER TABLE TB_IND_VERSION_TIME_COV ADD CONSTRAINT FK_TB_IND_VERSION_TIME_COV_I71 FOREIGN KEY (INDICATOR_VERSION_FK) REFERENCES TB_INDICATORS_VERSIONS (ID) ON DELETE CASCADE;

ALTER TABLE TB_IND_VERSION_MEAS_COV DROP CONSTRAINT FK_TB_IND_VERSION_MEAS_COV_I46;
ALTER TABLE TB_IND_VERSION_MEAS_COV ADD CONSTRAINT FK_TB_IND_VERSION_MEAS_COV_I46 FOREIGN KEY (INDICATOR_VERSION_FK) REFERENCES TB_INDICATORS_VERSIONS (ID) ON DELETE CASCADE;