-- Example values

-- CONFIGURATION
INSERT INTO TB_CONFIGURATION (ID, LAST_SUCCESSFUL_GPE_QUERY56) VALUES (SEQ_CONFIGURATION.nextval, to_date('2012/01/01 00:00:00', 'yyyy/mm/dd hh24:mi:ss'));

commit;
