ALTER TABLE TB_DATASETS ADD CONSTRAINT TB_DATASETS_DATASET_ID unique (DATASET_ID);
ALTER TABLE TB_DATASETS ADD CONSTRAINT TB_DATASETS_TABLE_NAME unique (TABLE_NAME);
ALTER TABLE TB_LOCALISED_STRINGS ADD CONSTRAINT TB_LOCALISED_STRINGS_LOCALE_INTERNATIONAL unique (LOCALE, INTERNATIONAL_STRING_FK);