-- ---------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- EDATOS-3637 - IESTADIS. Cargar las tablas de valores en eIndicadores
-- ---------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- Fichero elaborado a partir del esquema de temas IECM:TEMAS_MADRID(01.000)
-- Enlace. https://iestadis.edatos.io/structural-resources-internal/#structuralResources/categorySchemes/categoryScheme;id=IECM%253ATEMAS_MADRID(01.000)
-- ---------------------------------------------------------------------------------------------------------------------------------------------------------------------

-- Tema: 01
INSERT INTO TV_AREAS_TEMATICAS (ID_AREA_TEMATICA, DESCRIPCION) VALUES ('01', '1. Población');
INSERT INTO TV_AREAS_TEMATICAS (ID_AREA_TEMATICA, DESCRIPCION) VALUES ('01_01', '1.1 Evolución y estructura de la población');
INSERT INTO TV_AREAS_TEMATICAS (ID_AREA_TEMATICA, DESCRIPCION) VALUES ('01_02', '1.2 Censos de población y viviendas');
INSERT INTO TV_AREAS_TEMATICAS (ID_AREA_TEMATICA, DESCRIPCION) VALUES ('01_03', '1.3 Hogares y familias');
INSERT INTO TV_AREAS_TEMATICAS (ID_AREA_TEMATICA, DESCRIPCION) VALUES ('01_04', '1.4 Nacimientos y defunciones');
INSERT INTO TV_AREAS_TEMATICAS (ID_AREA_TEMATICA, DESCRIPCION) VALUES ('01_05', '1.5 Migraciones');
INSERT INTO TV_AREAS_TEMATICAS (ID_AREA_TEMATICA, DESCRIPCION) VALUES ('01_06', '1.6 Población extranjera');
INSERT INTO TV_AREAS_TEMATICAS (ID_AREA_TEMATICA, DESCRIPCION) VALUES ('01_07', '1.7 Movilidad y población estacional');
INSERT INTO TV_AREAS_TEMATICAS (ID_AREA_TEMATICA, DESCRIPCION) VALUES ('01_08', '1.8 Proyecciones de población');
INSERT INTO TV_AREAS_TEMATICAS (ID_AREA_TEMATICA, DESCRIPCION) VALUES ('01_09', '1.9 Onomástica');

-- Tema: 02
INSERT INTO TV_AREAS_TEMATICAS (ID_AREA_TEMATICA, DESCRIPCION) VALUES ('02', '2. Economía');
INSERT INTO TV_AREAS_TEMATICAS (ID_AREA_TEMATICA, DESCRIPCION) VALUES ('02_01', '2.1 Cuentas económicas');
INSERT INTO TV_AREAS_TEMATICAS (ID_AREA_TEMATICA, DESCRIPCION) VALUES ('02_02', '2.2 Empresas. Estructura');
INSERT INTO TV_AREAS_TEMATICAS (ID_AREA_TEMATICA, DESCRIPCION) VALUES ('02_03', '2.3 Coyuntura económica');
INSERT INTO TV_AREAS_TEMATICAS (ID_AREA_TEMATICA, DESCRIPCION) VALUES ('02_04', '2.4 Precios');
INSERT INTO TV_AREAS_TEMATICAS (ID_AREA_TEMATICA, DESCRIPCION) VALUES ('02_05', '2.5 Sector exterior');
INSERT INTO TV_AREAS_TEMATICAS (ID_AREA_TEMATICA, DESCRIPCION) VALUES ('02_06', '2.6 Inversión');
INSERT INTO TV_AREAS_TEMATICAS (ID_AREA_TEMATICA, DESCRIPCION) VALUES ('02_07', '2.7 I+D+I');
INSERT INTO TV_AREAS_TEMATICAS (ID_AREA_TEMATICA, DESCRIPCION) VALUES ('02_08', '2.8 TIC');
INSERT INTO TV_AREAS_TEMATICAS (ID_AREA_TEMATICA, DESCRIPCION) VALUES ('02_09', '2.9 Fiscalidad');

-- Tema: 03
INSERT INTO TV_AREAS_TEMATICAS (ID_AREA_TEMATICA, DESCRIPCION) VALUES ('03', '3. Sectores económicos');
INSERT INTO TV_AREAS_TEMATICAS (ID_AREA_TEMATICA, DESCRIPCION) VALUES ('03_01', '3.1 Sector agrario');
INSERT INTO TV_AREAS_TEMATICAS (ID_AREA_TEMATICA, DESCRIPCION) VALUES ('03_02', '3.2 Energía');
INSERT INTO TV_AREAS_TEMATICAS (ID_AREA_TEMATICA, DESCRIPCION) VALUES ('03_03', '3.3 Industria');
INSERT INTO TV_AREAS_TEMATICAS (ID_AREA_TEMATICA, DESCRIPCION) VALUES ('03_04', '3.4 Construcción');
INSERT INTO TV_AREAS_TEMATICAS (ID_AREA_TEMATICA, DESCRIPCION) VALUES ('03_05', '3.5 Comercio');
INSERT INTO TV_AREAS_TEMATICAS (ID_AREA_TEMATICA, DESCRIPCION) VALUES ('03_06', '3.6 Servicios');
INSERT INTO TV_AREAS_TEMATICAS (ID_AREA_TEMATICA, DESCRIPCION) VALUES ('03_07', '3.7 Transporte');
INSERT INTO TV_AREAS_TEMATICAS (ID_AREA_TEMATICA, DESCRIPCION) VALUES ('03_08', '3.8 Turismo');
INSERT INTO TV_AREAS_TEMATICAS (ID_AREA_TEMATICA, DESCRIPCION) VALUES ('03_09', '3.9 Sector financiero');
INSERT INTO TV_AREAS_TEMATICAS (ID_AREA_TEMATICA, DESCRIPCION) VALUES ('03_10', '3.10 Sector público');

-- Tema: 04
INSERT INTO TV_AREAS_TEMATICAS (ID_AREA_TEMATICA, DESCRIPCION) VALUES ('04', '4. Trabajo y sociedad');
INSERT INTO TV_AREAS_TEMATICAS (ID_AREA_TEMATICA, DESCRIPCION) VALUES ('04_01', '4.1 Relación con la actividad');
INSERT INTO TV_AREAS_TEMATICAS (ID_AREA_TEMATICA, DESCRIPCION) VALUES ('04_02', '4.2 Coste laboral y salarios');
INSERT INTO TV_AREAS_TEMATICAS (ID_AREA_TEMATICA, DESCRIPCION) VALUES ('04_03', '4.3 Condiciones laborales');
INSERT INTO TV_AREAS_TEMATICAS (ID_AREA_TEMATICA, DESCRIPCION) VALUES ('04_04', '4.4 Educación y formación (incluye formación continua en el trabajo)');
INSERT INTO TV_AREAS_TEMATICAS (ID_AREA_TEMATICA, DESCRIPCION) VALUES ('04_05', '4.5 Uso del tiempo');
INSERT INTO TV_AREAS_TEMATICAS (ID_AREA_TEMATICA, DESCRIPCION) VALUES ('04_06', '4.6 Cultura');
INSERT INTO TV_AREAS_TEMATICAS (ID_AREA_TEMATICA, DESCRIPCION) VALUES ('04_07', '4.7 Elecciones y participación ciudadana');
INSERT INTO TV_AREAS_TEMATICAS (ID_AREA_TEMATICA, DESCRIPCION) VALUES ('04_08', '4.8 Justicia y seguridad');
INSERT INTO TV_AREAS_TEMATICAS (ID_AREA_TEMATICA, DESCRIPCION) VALUES ('04_09', '4.9 Deportes');
INSERT INTO TV_AREAS_TEMATICAS (ID_AREA_TEMATICA, DESCRIPCION) VALUES ('04_10', '4.10 Juventud');

-- Tema: 05
INSERT INTO TV_AREAS_TEMATICAS (ID_AREA_TEMATICA, DESCRIPCION) VALUES ('05', '5. Condiciones de vida y protección social');
INSERT INTO TV_AREAS_TEMATICAS (ID_AREA_TEMATICA, DESCRIPCION) VALUES ('05_01', '5.1 Ingresos y condiciones de vida de los hogares');
INSERT INTO TV_AREAS_TEMATICAS (ID_AREA_TEMATICA, DESCRIPCION) VALUES ('05_02', '5.2 Servicios sociales y protección social');
INSERT INTO TV_AREAS_TEMATICAS (ID_AREA_TEMATICA, DESCRIPCION) VALUES ('05_03', '5.3 Salud');
INSERT INTO TV_AREAS_TEMATICAS (ID_AREA_TEMATICA, DESCRIPCION) VALUES ('05_04', '5.4 Servicios sanitarios');

-- Tema: 06
INSERT INTO TV_AREAS_TEMATICAS (ID_AREA_TEMATICA, DESCRIPCION) VALUES ('06', '6. Territorio y medio ambiente');
INSERT INTO TV_AREAS_TEMATICAS (ID_AREA_TEMATICA, DESCRIPCION) VALUES ('06_01', '6.1 Entorno físico y clima');
INSERT INTO TV_AREAS_TEMATICAS (ID_AREA_TEMATICA, DESCRIPCION) VALUES ('06_02', '6.2 Medio ambiente');
INSERT INTO TV_AREAS_TEMATICAS (ID_AREA_TEMATICA, DESCRIPCION) VALUES ('06_03', '6.3 Divisiones geográficas y administrativas');
INSERT INTO TV_AREAS_TEMATICAS (ID_AREA_TEMATICA, DESCRIPCION) VALUES ('06_04', '6.4 Usos del suelo y planificación');
INSERT INTO TV_AREAS_TEMATICAS (ID_AREA_TEMATICA, DESCRIPCION) VALUES ('06_05', '6.5 Viviendas, edificios y locales');
INSERT INTO TV_AREAS_TEMATICAS (ID_AREA_TEMATICA, DESCRIPCION) VALUES ('06_06', '6.6 Infraestructuras');

-- Tema: 07
INSERT INTO TV_AREAS_TEMATICAS (ID_AREA_TEMATICA, DESCRIPCION) VALUES ('07', '7. Metodología y normalización');
INSERT INTO TV_AREAS_TEMATICAS (ID_AREA_TEMATICA, DESCRIPCION) VALUES ('07_01', '7.1 Metodología y normalización');

-- Tema: 08
INSERT INTO TV_AREAS_TEMATICAS (ID_AREA_TEMATICA, DESCRIPCION) VALUES ('08', '8. Registros estadísticos y directorios');
INSERT INTO TV_AREAS_TEMATICAS (ID_AREA_TEMATICA, DESCRIPCION) VALUES ('08_01', '8.1 Registros estadísticos y directorios');

-- Tema: 09
INSERT INTO TV_AREAS_TEMATICAS (ID_AREA_TEMATICA, DESCRIPCION) VALUES ('09', '9. Georreferenciación y estadística de base territorial');
INSERT INTO TV_AREAS_TEMATICAS (ID_AREA_TEMATICA, DESCRIPCION) VALUES ('09_01', '9.1 Georreferenciación y estadística de base territorial');

-- Tema: 10
INSERT INTO TV_AREAS_TEMATICAS (ID_AREA_TEMATICA, DESCRIPCION) VALUES ('10', '10. Indicadores y estadística de síntesis');
INSERT INTO TV_AREAS_TEMATICAS (ID_AREA_TEMATICA, DESCRIPCION) VALUES ('10_01', '10.1 Estadística de síntesis');
INSERT INTO TV_AREAS_TEMATICAS (ID_AREA_TEMATICA, DESCRIPCION) VALUES ('10_02', '10.2 Sistemas de indicadores estadísticos');

-- Tema: 11
INSERT INTO TV_AREAS_TEMATICAS (ID_AREA_TEMATICA, DESCRIPCION) VALUES ('11', '11. Difusión y promoción de la estadística');
INSERT INTO TV_AREAS_TEMATICAS (ID_AREA_TEMATICA, DESCRIPCION) VALUES ('11_01', '11.1 Difusión y promoción de la estadística');

commit;