-- Drop many to many relations
    
    	
DROP TABLE TB_INDIC_INST_GEO_VALUES CASCADE CONSTRAINTS PURGE;

-- Drop normal entities

    	
DROP TABLE TB_TASKS CASCADE CONSTRAINTS PURGE;    


DROP TABLE TB_LOCALISED_STRINGS CASCADE CONSTRAINTS PURGE;

    	
DROP TABLE TB_INDICATORS_SYSTEMS_HIST CASCADE CONSTRAINTS PURGE;

    	
DROP TABLE TB_IND_VERSION_TIME_COV CASCADE CONSTRAINTS PURGE;

    	
DROP TABLE TB_IND_VERSION_MEAS_COV CASCADE CONSTRAINTS PURGE;

    	
DROP TABLE TB_TRANSLATIONS CASCADE CONSTRAINTS PURGE;


DROP TABLE TB_INDIC_VERSION_LAST_VALUE CASCADE CONSTRAINTS PURGE;
    	

DROP TABLE TB_IND_VERSION_GEO_COV CASCADE CONSTRAINTS PURGE;

    	
DROP TABLE TB_INDIC_INST_LAST_VALUE CASCADE CONSTRAINTS PURGE;

    	
DROP TABLE TB_DIMENSIONS CASCADE CONSTRAINTS PURGE;

    	
DROP TABLE TB_ELEMENTS_LEVELS CASCADE CONSTRAINTS PURGE;

    	
DROP TABLE TB_INDIC_SYSTEMS_VERSIONS CASCADE CONSTRAINTS PURGE;

    	
DROP TABLE TB_INDICATORS_SYSTEMS CASCADE CONSTRAINTS PURGE;

    	
DROP TABLE TB_INDICATORS_INSTANCES CASCADE CONSTRAINTS PURGE;

    	
DROP TABLE TB_DATA_SOURCES_VARIABLES CASCADE CONSTRAINTS PURGE;

    	
DROP TABLE TB_DATA_SOURCES CASCADE CONSTRAINTS PURGE;

    	
DROP TABLE TB_RATES_DERIVATIONS CASCADE CONSTRAINTS PURGE;

    	
DROP TABLE TB_INDICATORS_VERSIONS CASCADE CONSTRAINTS PURGE;

    	
DROP TABLE TB_QUANTITIES CASCADE CONSTRAINTS PURGE;

    	
DROP TABLE TB_LIS_GEOGR_VALUES CASCADE CONSTRAINTS PURGE;

    	
DROP TABLE TB_LIS_GEOGR_GRANULARITIES CASCADE CONSTRAINTS PURGE;

    	
DROP TABLE TB_LIS_QUANTITIES_UNITS CASCADE CONSTRAINTS PURGE;

    	
DROP TABLE TB_LIS_UNITS_MULTIPLIERS CASCADE CONSTRAINTS PURGE;

    	
DROP TABLE TB_INDICATORS CASCADE CONSTRAINTS PURGE;

    	
DROP TABLE TB_EXTERNAL_ITEMS CASCADE CONSTRAINTS PURGE;

    	
DROP TABLE TB_INTERNATIONAL_STRINGS CASCADE CONSTRAINTS PURGE;


    	
DROP TABLE TB_CONFIGURATION CASCADE CONSTRAINTS PURGE;


-- Drop pk sequence
    
DROP sequence SEQ_INDIC_SYSTEMS_VERSIONS;
DROP sequence SEQ_INDICATORS_SYSTEMS;
DROP sequence SEQ_INDICATORS_INSTANCES;
DROP sequence SEQ_INDICATORS_VERSIONS;
DROP sequence SEQ_INDICATORS;
DROP sequence SEQ_I18NSTRS;
DROP sequence SEQ_L10NSTRS;
DROP sequence SEQ_DIMENSIONS;
DROP sequence SEQ_ELEMENTS_LEVELS;
DROP sequence SEQ_DATA_SOURCES;
DROP sequence SEQ_DATA_SOURCES_VARIABLES;
DROP sequence SEQ_QUANTITIES;
DROP sequence SEQ_INDICATORS_SYSTEMS_HIST;
DROP sequence SEQ_QUANTITIES_UNITS;
DROP sequence SEQ_RATES_DERIVATIONS;
DROP sequence SEQ_GEOGR_VALUES;
DROP sequence SEQ_GEOGR_GRANULARITIES;
DROP sequence SEQ_CONFIGURATION;
DROP sequence SEQ_TRANSLATIONS;
DROP sequence SEQ_UNITS_MULTIPLIERS;
DROP sequence SEQ_EXTERNAL_ITEMS;
DROP sequence SEQ_INDIC_VERSION_LAST_VALUE;
DROP sequence SEQ_INDIC_INST_LAST_VALUE;
DROP sequence SEQ_IND_VERSION_GEO_COV;
DROP sequence SEQ_IND_VERSION_MEAS_COV;
DROP sequence SEQ_IND_VERSION_TIME_COV;
DROP sequence SEQ_TASKS;
