
-- --------------------------------------------------------------------------------------------------
-- EDATOS-4185 - Añadir metadato elemento de tema a los indicadores
-- 
-- Crear tabla de caché de temas en indicadores
-- --------------------------------------------------------------------------------------------------

CREATE TABLE TB_CATEGORY_CACHE (
  ID BIGINT NOT NULL,
  CATEGORY_CODE VARCHAR(255) NOT NULL,
  TITLE_FK BIGINT NOT NULL,
  CATEGORY_ELEMENT_CODE VARCHAR(255) NOT NULL,
  UPDATE_DATE_TZ VARCHAR(50),
  UPDATE_DATE TIMESTAMP,
  UUID VARCHAR(36) NOT NULL,
  CREATED_DATE_TZ VARCHAR(50),
  CREATED_DATE TIMESTAMP,
  CREATED_BY VARCHAR(50),
  LAST_UPDATED_TZ VARCHAR(50),
  LAST_UPDATED TIMESTAMP,
  LAST_UPDATED_BY VARCHAR(50)
);

ALTER TABLE TB_CATEGORY_CACHE ADD CONSTRAINT PK_TB_CATEGORY_CACHE
	PRIMARY KEY (ID);

ALTER TABLE TB_CATEGORY_CACHE ADD CONSTRAINT FK_TB_CATEGORY_CACHE_TITLE_FK
	FOREIGN KEY (TITLE_FK) REFERENCES TB_INTERNATIONAL_STRINGS (ID);

-- TO BETTER PERFORMANCE OF delete in tb_international_string table
CREATE INDEX pk_TB_CATEGORY_CACHE_TITLE_FK ON TB_CATEGORY_CACHE USING btree (TITLE_FK);
CREATE INDEX pk_TB_CATEGORY_CACHE_CATEGORY_ELEMENT_CODE ON TB_CATEGORY_CACHE USING btree (CATEGORY_ELEMENT_CODE);
CREATE INDEX pk_TB_CATEGORY_CACHE_CATEGORY_CODE ON TB_CATEGORY_CACHE USING btree (CATEGORY_CODE);

CREATE SEQUENCE SEQ_CATEGORY_CACHE;

COMMIT;
