----------------------------------------------------------------------------------------
-- EDATOS-5077 - Fijar el valor "Islas baleares" para que aparezca primero al configurar el widget solo para la granularidad de CCAA
-- -----------------------------------------------------------------------------------------------

-- La propiedad ya puede existir por haberla creado otra aplicación.
INSERT INTO TB_DATA_CONFIGURATIONS (ID, VERSION, SYSTEM_PROPERTY, CONF_KEY, CONF_VALUE, EXTERNALLY_PUBLISHED)
VALUES (GET_NEXT_SEQUENCE_VALUE('DATA_CONFIGURATIONS'), 1, true, 'edatos.shared.first_territory', 'FILL_ME', true)
    ON CONFLICT (CONF_KEY) DO NOTHING;
-- Ejemplo DEMO y DESARROLLO:   INSERT INTO TB_DATA_CONFIGURATIONS (ID, VERSION, SYSTEM_PROPERTY, CONF_KEY, CONF_VALUE, EXTERNALLY_PUBLISHED) VALUES (GET_NEXT_SEQUENCE_VALUE('DATA_CONFIGURATIONS'), 1, true, 'edatos.shared.first_territory', 'CCAA_CANARIAS', true) ON CONFLICT DO NOTHING;
-- Ejemplo PRO ISTAC:           INSERT INTO TB_DATA_CONFIGURATIONS (ID, VERSION, SYSTEM_PROPERTY, CONF_KEY, CONF_VALUE, EXTERNALLY_PUBLISHED) VALUES (GET_NEXT_SEQUENCE_VALUE('DATA_CONFIGURATIONS'), 1, true, 'edatos.shared.first_territory', 'CCAA_CANARIAS', true) ON CONFLICT DO NOTHING;
-- Ejemplo PRO IBESTAT:         INSERT INTO TB_DATA_CONFIGURATIONS (ID, VERSION, SYSTEM_PROPERTY, CONF_KEY, CONF_VALUE, EXTERNALLY_PUBLISHED) VALUES (GET_NEXT_SEQUENCE_VALUE('DATA_CONFIGURATIONS'), 1, true, 'edatos.shared.first_territory', 'CCAA_ILLES_BALEARS', true) ON CONFLICT DO NOTHING;
-- Ejemplo PRO IESTADIS:        INSERT INTO TB_DATA_CONFIGURATIONS (ID, VERSION, SYSTEM_PROPERTY, CONF_KEY, CONF_VALUE, EXTERNALLY_PUBLISHED) VALUES (GET_NEXT_SEQUENCE_VALUE('DATA_CONFIGURATIONS'), 1, true, 'edatos.shared.first_territory', 'CCAA_MADRID', true) ON CONFLICT DO NOTHING;

UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'DATA_CONFIGURATIONS';
commit;
