

CREATE TABLE TB_IND_VERSION_GEO_COV (
  ID NUMBER(19) NOT NULL,
  GEOGRAPHICAL_VALUE_FK NUMBER(19) NOT NULL,
  INDICATOR_VERSION_FK NUMBER(19) NOT NULL
);

ALTER TABLE TB_IND_VERSION_GEO_COV ADD CONSTRAINT PK_TB_IND_VERSION_GEO_COV
	PRIMARY KEY (ID)
;

ALTER TABLE TB_IND_VERSION_GEO_COV
	ADD CONSTRAINT UQ_TB_IND_VERSION_GEO_COV UNIQUE (GEOGRAPHICAL_VALUE_FK, INDICATOR_VERSION_FK)
;

  
ALTER TABLE TB_IND_VERSION_GEO_COV ADD CONSTRAINT FK_TB_IND_VERSION_GEO_COV_GE87
	FOREIGN KEY (GEOGRAPHICAL_VALUE_FK) REFERENCES TB_LIS_GEOGR_VALUES (ID)
;
ALTER TABLE TB_IND_VERSION_GEO_COV ADD CONSTRAINT FK_TB_IND_VERSION_GEO_COV_IN03
	FOREIGN KEY (INDICATOR_VERSION_FK) REFERENCES TB_INDICATORS_VERSIONS (ID)
;

CREATE sequence SEQ_IND_VERSION_GEO_COV;

    	
CREATE TABLE TB_IND_VERSION_MEAS_COV (
  ID NUMBER(19) NOT NULL,
  MEASURE_CODE VARCHAR2(255 CHAR) NOT NULL,
  INDICATOR_VERSION_FK NUMBER(19) NOT NULL,
  TRANSLATION NUMBER(19)
);

		
ALTER TABLE TB_IND_VERSION_MEAS_COV ADD CONSTRAINT PK_TB_IND_VERSION_MEAS_COV
	PRIMARY KEY (ID)
;

ALTER TABLE TB_IND_VERSION_MEAS_COV
	ADD CONSTRAINT UQ_TB_IND_VERSION_MEAS_COV UNIQUE (MEASURE_CODE, INDICATOR_VERSION_FK)
;

ALTER TABLE TB_IND_VERSION_MEAS_COV ADD CONSTRAINT FK_TB_IND_VERSION_MEAS_COV_I46
	FOREIGN KEY (INDICATOR_VERSION_FK) REFERENCES TB_INDICATORS_VERSIONS (ID)
;
ALTER TABLE TB_IND_VERSION_MEAS_COV ADD CONSTRAINT FK_TB_IND_VERSION_MEAS_COV_T35
	FOREIGN KEY (TRANSLATION) REFERENCES TB_TRANSLATIONS (ID)
;

CREATE sequence SEQ_IND_VERSION_MEAS_COV;

    	
CREATE TABLE TB_IND_VERSION_TIME_COV (
  ID NUMBER(19) NOT NULL,
  TIME_VALUE VARCHAR2(255 CHAR) NOT NULL,
  TIME_GRANULARITY VARCHAR2(255 CHAR) NOT NULL,
  INDICATOR_VERSION_FK NUMBER(19) NOT NULL,
  TRANSLATION NUMBER(19),
  GRANULARITY_TRANSLATION NUMBER(19)
);

		
ALTER TABLE TB_IND_VERSION_TIME_COV ADD CONSTRAINT PK_TB_IND_VERSION_TIME_COV
	PRIMARY KEY (ID)
;


ALTER TABLE TB_IND_VERSION_TIME_COV
	ADD CONSTRAINT UQ_TB_IND_VERSION_TIME_COV UNIQUE (TIME_VALUE, INDICATOR_VERSION_FK)
;


  
ALTER TABLE TB_IND_VERSION_TIME_COV ADD CONSTRAINT FK_TB_IND_VERSION_TIME_COV_I71
	FOREIGN KEY (INDICATOR_VERSION_FK) REFERENCES TB_INDICATORS_VERSIONS (ID)
;
ALTER TABLE TB_IND_VERSION_TIME_COV ADD CONSTRAINT FK_TB_IND_VERSION_TIME_COV_T50
	FOREIGN KEY (TRANSLATION) REFERENCES TB_TRANSLATIONS (ID)
;
ALTER TABLE TB_IND_VERSION_TIME_COV ADD CONSTRAINT FK_TB_IND_VERSION_TIME_COV_G83
	FOREIGN KEY (GRANULARITY_TRANSLATION) REFERENCES TB_TRANSLATIONS (ID)
;


CREATE sequence SEQ_IND_VERSION_TIME_COV;

commit;
