-- ----------------------------------------------------------------------------------------------------
-- INDISTAC-775 - Poder llevar a cabo la edición de las tablas de valores desde el propio aplicativo
-- ----------------------------------------------------------------------------------------------------

-- Añadir constraint de que el valor del unit multiplier sea único
ALTER TABLE TB_LIS_UNITS_MULTIPLIERS ADD CONSTRAINT UNIT_MULTIPLIER UNIQUE(UNIT_MULTIPLIER);

-- Añadir campos a la entidad TB_LIS_QUANTITIES_UNITS
ALTER TABLE TB_LIS_QUANTITIES_UNITS ADD (
  UPDATE_DATE_TZ VARCHAR2(50 CHAR),
  UPDATE_DATE TIMESTAMP,
  CREATED_DATE_TZ VARCHAR2(50 CHAR),
  CREATED_DATE TIMESTAMP,
  CREATED_BY VARCHAR2(50 CHAR),
  LAST_UPDATED_TZ VARCHAR2(50 CHAR),
  LAST_UPDATED TIMESTAMP,
  LAST_UPDATED_BY VARCHAR2(50 CHAR),
  VERSION NUMBER(19) DEFAULT 0 NOT NULL
);

-- Añadir campos a la entidad TB_LIS_GEOGR_GRANULARITIES
ALTER TABLE TB_LIS_GEOGR_GRANULARITIES ADD (
  UPDATE_DATE_TZ VARCHAR2(50 CHAR),
  UPDATE_DATE TIMESTAMP,
  CREATED_DATE_TZ VARCHAR2(50 CHAR),
  CREATED_DATE TIMESTAMP,
  CREATED_BY VARCHAR2(50 CHAR),
  LAST_UPDATED_TZ VARCHAR2(50 CHAR),
  LAST_UPDATED TIMESTAMP,
  LAST_UPDATED_BY VARCHAR2(50 CHAR),
  VERSION NUMBER(19) DEFAULT 0 NOT NULL
);

-- Añadir campos a la entidad TB_LIS_GEOGR_VALUES
ALTER TABLE TB_LIS_GEOGR_VALUES ADD (
  UPDATE_DATE_TZ VARCHAR2(50 CHAR),
  UPDATE_DATE TIMESTAMP,
  CREATED_DATE_TZ VARCHAR2(50 CHAR),
  CREATED_DATE TIMESTAMP,
  CREATED_BY VARCHAR2(50 CHAR),
  LAST_UPDATED_TZ VARCHAR2(50 CHAR),
  LAST_UPDATED TIMESTAMP,
  LAST_UPDATED_BY VARCHAR2(50 CHAR),
  VERSION NUMBER(19) DEFAULT 0 NOT NULL
);

-- Añadir campos a la entidad TB_LIS_UNITS_MULTIPLIERS
ALTER TABLE TB_LIS_UNITS_MULTIPLIERS ADD (
  UPDATE_DATE_TZ VARCHAR2(50 CHAR),
  UPDATE_DATE TIMESTAMP,
  CREATED_DATE_TZ VARCHAR2(50 CHAR),
  CREATED_DATE TIMESTAMP,
  CREATED_BY VARCHAR2(50 CHAR),
  LAST_UPDATED_TZ VARCHAR2(50 CHAR),
  LAST_UPDATED TIMESTAMP,
  LAST_UPDATED_BY VARCHAR2(50 CHAR),
  VERSION NUMBER(19) DEFAULT 0 NOT NULL
);