ALTER TABLE TB_DATASETS ADD CONSTRAINT DATASET_ID UNIQUE(DATASET_ID);
ALTER TABLE TB_DATASETS ADD CONSTRAINT TABLE_NAME UNIQUE(TABLE_NAME);

ALTER TABLE TB_LOCALISED_STRINGS ADD CONSTRAINT LOCALE_INTERNATIONAL UNIQUE(LOCALE, INTERNATIONAL_STRING_FK) DEFERRABLE INITIALLY DEFERRED;