-- Drop many to many relations
    
    	
DROP TABLE TB_INDIC_INST_GEO_VALUES CASCADE;

-- Drop normal entities
    
    	
DROP TABLE TB_TASKS CASCADE;

    	
DROP TABLE TB_LOCALISED_STRINGS CASCADE;

    	
DROP TABLE TB_INDICATORS_SYSTEMS_HIST CASCADE;

    	
DROP TABLE TB_IND_VERSION_TIME_COV CASCADE;

    	
DROP TABLE TB_IND_VERSION_MEAS_COV CASCADE;

    	
DROP TABLE TB_TRANSLATIONS CASCADE;

    	
DROP TABLE TB_INDIC_VERSION_LAST_VALUE CASCADE;

    	
DROP TABLE TB_IND_VERSION_GEO_COV CASCADE;

    	
DROP TABLE TB_INDIC_INST_LAST_VALUE CASCADE;

    	
DROP TABLE TB_DIMENSIONS CASCADE;

    	
DROP TABLE TB_ELEMENTS_LEVELS CASCADE;

    	
DROP TABLE TB_INDIC_SYSTEMS_VERSIONS CASCADE;

    	
DROP TABLE TB_INDICATORS_SYSTEMS CASCADE;

    	
DROP TABLE TB_INDICATORS_INSTANCES CASCADE;

    	
DROP TABLE TB_DATA_SOURCES_VARIABLES CASCADE;

    	
DROP TABLE TB_DATA_SOURCES CASCADE;

    	
DROP TABLE TB_RATES_DERIVATIONS CASCADE;

    	
DROP TABLE TB_INDICATORS_VERSIONS CASCADE;

    	
DROP TABLE TB_QUANTITIES CASCADE;

    	
DROP TABLE TB_LIS_GEOGR_VALUES CASCADE;

    	
DROP TABLE TB_LIS_GEOGR_GRANULARITIES CASCADE;

    	
DROP TABLE TB_LIS_QUANTITIES_UNITS CASCADE;

    	
DROP TABLE TB_LIS_UNITS_MULTIPLIERS CASCADE;

    	
DROP TABLE TB_INDICATORS CASCADE;

    	
DROP TABLE TB_EXTERNAL_ITEMS CASCADE;

    	
DROP TABLE TB_INTERNATIONAL_STRINGS CASCADE;


    	
DROP TABLE TB_CONFIGURATION CASCADE;


-- Drop pk sequence
    
DROP sequence SEQ_INDIC_SYSTEMS_VERSIONS;
DROP sequence SEQ_INDICATORS_SYSTEMS;
DROP sequence SEQ_INDICATORS_INSTANCES;
DROP sequence SEQ_INDICATORS_VERSIONS;
DROP sequence SEQ_INDICATORS;
DROP sequence SEQ_I18NSTRS;
DROP sequence SEQ_L10NSTRS;
DROP sequence SEQ_DIMENSIONS;
DROP sequence SEQ_ELEMENTS_LEVELS;
DROP sequence SEQ_DATA_SOURCES;
DROP sequence SEQ_DATA_SOURCES_VARIABLES;
DROP sequence SEQ_QUANTITIES;
DROP sequence SEQ_INDICATORS_SYSTEMS_HIST;
DROP sequence SEQ_QUANTITIES_UNITS;
DROP sequence SEQ_RATES_DERIVATIONS;
DROP sequence SEQ_GEOGR_VALUES;
DROP sequence SEQ_GEOGR_GRANULARITIES;
DROP sequence SEQ_CONFIGURATION;
DROP sequence SEQ_TRANSLATIONS;
DROP sequence SEQ_UNITS_MULTIPLIERS;
DROP sequence SEQ_EXTERNAL_ITEMS;
DROP sequence SEQ_INDIC_VERSION_LAST_VALUE;
DROP sequence SEQ_INDIC_INST_LAST_VALUE;
DROP sequence SEQ_IND_VERSION_GEO_COV;
DROP sequence SEQ_IND_VERSION_MEAS_COV;
DROP sequence SEQ_IND_VERSION_TIME_COV;
DROP sequence SEQ_TASKS;
