-- Drop many to many relations
    
-- Drop normal entities
    
    	
DROP TABLE TB_LOCALISED_STRINGS CASCADE CONSTRAINTS PURGE;

    	
DROP TABLE TB_TRANSLATIONS CASCADE CONSTRAINTS PURGE;


    	
DROP TABLE TB_DIMENSIONS CASCADE CONSTRAINTS PURGE;

    	
DROP TABLE TB_ELEMENTS_LEVELS CASCADE CONSTRAINTS PURGE;

    	
DROP TABLE TB_INDIC_SYSTEMS_VERSIONS CASCADE CONSTRAINTS PURGE;

    	
DROP TABLE TB_INDICATORS_SYSTEMS CASCADE CONSTRAINTS PURGE;

    	
DROP TABLE TB_INDICATORS_INSTANCES CASCADE CONSTRAINTS PURGE;

    	
DROP TABLE TB_DATA_SOURCES_VARIABLES CASCADE CONSTRAINTS PURGE;

    	
DROP TABLE TB_DATA_SOURCES CASCADE CONSTRAINTS PURGE;

    	
DROP TABLE TB_RATES_DERIVATIONS CASCADE CONSTRAINTS PURGE;

    	
DROP TABLE TB_INDICATORS_VERSIONS CASCADE CONSTRAINTS PURGE;

    	
DROP TABLE TB_QUANTITIES CASCADE CONSTRAINTS PURGE;

    	
DROP TABLE TB_LIS_GEOGR_VALUES CASCADE CONSTRAINTS PURGE;

    	
DROP TABLE TB_LIS_GEOGR_GRANULARITIES CASCADE CONSTRAINTS PURGE;

    	
DROP TABLE TB_LIS_QUANTITIES_UNITS CASCADE CONSTRAINTS PURGE;

    	
DROP TABLE TB_INDICATORS CASCADE CONSTRAINTS PURGE;

    	
DROP TABLE TB_INTERNATIONAL_STRINGS CASCADE CONSTRAINTS PURGE;


    	
DROP TABLE TB_CONFIGURATION CASCADE CONSTRAINTS PURGE;


-- Drop pk sequence
    
DROP sequence SEQ_INDIC_SYSTEMS_VERSIONS;
DROP sequence SEQ_INDICATORS_SYSTEMS;
DROP sequence SEQ_INDICATORS_INSTANCES;
DROP sequence SEQ_INDICATORS_VERSIONS;
DROP sequence SEQ_INDICATORS;
DROP sequence SEQ_I18NSTRS;
DROP sequence SEQ_L10NSTRS;
DROP sequence SEQ_DIMENSIONS;
DROP sequence SEQ_ELEMENTS_LEVELS;
DROP sequence SEQ_DATA_SOURCES;
DROP sequence SEQ_DATA_SOURCES_VARIABLES;
DROP sequence SEQ_QUANTITIES;
DROP sequence SEQ_QUANTITIES_UNITS;
DROP sequence SEQ_RATES_DERIVATIONS;
DROP sequence SEQ_GEOGR_VALUES;
DROP sequence SEQ_GEOGR_GRANULARITIES;
DROP sequence SEQ_TRANSLATIONS;