-- Example values

-- SUBJECTS
INSERT INTO TV_AREAS_TEMATICAS (ID_AREA_TEMATICA, DESCRIPCION) VALUES ('EDUCACION', 'Educación');
INSERT INTO TV_AREAS_TEMATICAS (ID_AREA_TEMATICA, DESCRIPCION) VALUES ('POLITICA_ECON', 'Política económica');
INSERT INTO TV_AREAS_TEMATICAS (ID_AREA_TEMATICA, DESCRIPCION) VALUES ('SALUD', 'Salud');
INSERT INTO TV_AREAS_TEMATICAS (ID_AREA_TEMATICA, DESCRIPCION) VALUES ('MEDIO_AMBIENTE', 'Medio ambiente');
