-- Unit multipliers

CREATE TABLE TB_LIS_UNITS_MULTIPLIERS (
 ID NUMBER(19) NOT NULL,
 UNIT_MULTIPLIER NUMBER(10),
 UUID VARCHAR2(36) NOT NULL,
 TITLE_FK NUMBER(19)
);

ALTER TABLE TB_LIS_UNITS_MULTIPLIERS ADD CONSTRAINT PK_TB_LIS_UNITS_MULTIPLIERS
	PRIMARY KEY (ID)
;

ALTER TABLE TB_LIS_UNITS_MULTIPLIERS
  ADD CONSTRAINT UQ_TB_LIS_UNITS_MULTIPLIERS UNIQUE (UUID)
;

ALTER TABLE TB_LIS_UNITS_MULTIPLIERS ADD CONSTRAINT FK_TB_LIS_UNITS_MULTIPLIERS_37
	FOREIGN KEY (TITLE_FK) REFERENCES TB_INTERNATIONAL_STRINGS (ID)
;

CREATE sequence SEQ_UNITS_MULTIPLIERS;

-- Inserts
INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (SEQ_I18NSTRS.nextval, 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.nextval, 'Unidades', 'es', SEQ_I18NSTRS.currval, 1);
INSERT INTO TB_LIS_UNITS_MULTIPLIERS (ID, UNIT_MULTIPLIER, UUID, TITLE_FK) values (SEQ_UNITS_MULTIPLIERS.nextval, 1, '1', SEQ_I18NSTRS.currval);

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (SEQ_I18NSTRS.nextval, 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.nextval, 'Decenas', 'es', SEQ_I18NSTRS.currval, 1);
INSERT INTO TB_LIS_UNITS_MULTIPLIERS (ID, UNIT_MULTIPLIER, UUID, TITLE_FK) values (SEQ_UNITS_MULTIPLIERS.nextval, 10, '2', SEQ_I18NSTRS.currval);

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (SEQ_I18NSTRS.nextval, 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.nextval, 'Cientos', 'es', SEQ_I18NSTRS.currval, 1);
INSERT INTO TB_LIS_UNITS_MULTIPLIERS (ID, UNIT_MULTIPLIER, UUID, TITLE_FK) values (SEQ_UNITS_MULTIPLIERS.nextval, 100, '3', SEQ_I18NSTRS.currval);

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (SEQ_I18NSTRS.nextval, 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.nextval, 'Miles', 'es', SEQ_I18NSTRS.currval, 1);
INSERT INTO TB_LIS_UNITS_MULTIPLIERS (ID, UNIT_MULTIPLIER, UUID, TITLE_FK) values (SEQ_UNITS_MULTIPLIERS.nextval, 1000, '4', SEQ_I18NSTRS.currval);

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (SEQ_I18NSTRS.nextval, 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.nextval, 'Decenas de miles', 'es', SEQ_I18NSTRS.currval, 1);
INSERT INTO TB_LIS_UNITS_MULTIPLIERS (ID, UNIT_MULTIPLIER, UUID, TITLE_FK) values (SEQ_UNITS_MULTIPLIERS.nextval, 10000, '5', SEQ_I18NSTRS.currval);

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (SEQ_I18NSTRS.nextval, 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.nextval, 'Cientos de miles', 'es', SEQ_I18NSTRS.currval, 1);
INSERT INTO TB_LIS_UNITS_MULTIPLIERS (ID, UNIT_MULTIPLIER, UUID, TITLE_FK) values (SEQ_UNITS_MULTIPLIERS.nextval, 100000, '6', SEQ_I18NSTRS.currval);

INSERT INTO TB_INTERNATIONAL_STRINGS (ID, VERSION) values (SEQ_I18NSTRS.nextval, 1);
INSERT INTO TB_LOCALISED_STRINGS (ID, LABEL, LOCALE, INTERNATIONAL_STRING_FK, VERSION) values (SEQ_L10NSTRS.nextval, 'Millones', 'es', SEQ_I18NSTRS.currval, 1);
INSERT INTO TB_LIS_UNITS_MULTIPLIERS (ID, UNIT_MULTIPLIER, UUID, TITLE_FK) values (SEQ_UNITS_MULTIPLIERS.nextval, 1000000, '7', SEQ_I18NSTRS.currval);
