ALTER TABLE TB_EXTERNAL_ITEMS MODIFY  (
    MANAGEMENT_APP_URL VARCHAR2(4000),
    TYPE VARCHAR2(255)
);

ALTER TABLE TB_LIS_QUANTITIES_UNITS MODIFY  (
    SYMBOL_POSITION VARCHAR2(255)
);

ALTER TABLE TB_QUANTITIES MODIFY  (
    QUANTITY_TYPE VARCHAR2(255)
);

ALTER TABLE TB_INDICATORS_VERSIONS MODIFY  (
    PROC_STATUS VARCHAR2(255)
);

ALTER TABLE TB_RATES_DERIVATIONS MODIFY  (
    METHOD_TYPE VARCHAR2(255),
    ROUNDING VARCHAR2(255)
);

ALTER TABLE TB_DATA_SOURCES MODIFY  (
    TIME_VALUE VARCHAR2(255)
);

ALTER TABLE TB_INDICATORS_INSTANCES MODIFY  (
    TIME_GRANULARITY VARCHAR2(255)
);

ALTER TABLE TB_INDIC_SYSTEMS_VERSIONS MODIFY  (
    PROC_STATUS VARCHAR2(255)
);