Alter Table Tb_Indic_Inst_Geo_Values
rename column GEOGRAPHICAL_VALUE to GEOGRAPHICAL_VALUE_FK;

Alter Table Tb_Indic_Inst_Geo_Values
rename column TB_INDICATORS_INSTANCES to INDICATOR_INSTANCE_FK;

ALTER TABLE TB_INDIC_INST_GEO_VALUES ADD CONSTRAINT PK_TB_INDIC_INST_GEO_VALUES
	PRIMARY KEY (GEOGRAPHICAL_VALUE_FK, INDICATOR_INSTANCE_FK)
;
