CREATE TABLE TB_EXTERNAL_ITEMS (
  ID NUMBER(19) NOT NULL,
  CODE VARCHAR2(255) NOT NULL,
  URI VARCHAR2(4000) NOT NULL,
  URN VARCHAR2(4000) NOT NULL,
  MANAGEMENT_APP_URL VARCHAR2(255),
  VERSION NUMBER(19) NOT NULL,
  TITLE_FK NUMBER(19),
  TYPE VARCHAR2(40) NOT NULL
);

ALTER TABLE TB_EXTERNAL_ITEMS ADD CONSTRAINT PK_TB_EXTERNAL_ITEMS
    PRIMARY KEY (ID)
;

ALTER TABLE TB_EXTERNAL_ITEMS
    ADD CONSTRAINT UQ_TB_EXTERNAL_ITEMS UNIQUE (ID)
;

ALTER TABLE TB_EXTERNAL_ITEMS ADD CONSTRAINT FK_TB_EXTERNAL_ITEMS_TITLE_FK
    FOREIGN KEY (TITLE_FK) REFERENCES TB_INTERNATIONAL_STRINGS (ID)
;

create sequence SEQ_EXTERNAL_ITEMS;