
-- Add new column
ALTER TABLE TB_LIS_GEOGR_VALUES ADD GLOBAL_ORDER VARCHAR2(255);

-- Update values ****
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES' WHERE CODE = 'ES';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES01' WHERE CODE = 'ES61';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES02' WHERE CODE = 'ES24';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES03' WHERE CODE = 'ES12';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES04' WHERE CODE = 'ES53';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES05' WHERE CODE = 'ES70';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES06' WHERE CODE = 'ES13';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES07' WHERE CODE = 'ES41';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES08' WHERE CODE = 'ES42';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES09' WHERE CODE = 'ES51';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES10' WHERE CODE = 'ES52';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES11' WHERE CODE = 'ES43';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES12' WHERE CODE = 'ES11';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES13' WHERE CODE = 'ES30';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES14' WHERE CODE = 'ES62';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES15' WHERE CODE = 'ES22';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES16' WHERE CODE = 'ES21';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES17' WHERE CODE = 'ES23';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES18' WHERE CODE = 'ES63';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES19' WHERE CODE = 'ES64';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES0101' WHERE CODE = 'ES611';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES0102' WHERE CODE = 'ES612';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES0103' WHERE CODE = 'ES613';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES0104' WHERE CODE = 'ES614';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES0105' WHERE CODE = 'ES615';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES0106' WHERE CODE = 'ES616';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES0107' WHERE CODE = 'ES617';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES0108' WHERE CODE = 'ES618';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES0201' WHERE CODE = 'ES241';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES0202' WHERE CODE = 'ES242';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES0203' WHERE CODE = 'ES243';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES0501' WHERE CODE = 'ES701';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES0502' WHERE CODE = 'ES702';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES0701' WHERE CODE = 'ES411';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES0702' WHERE CODE = 'ES412';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES0703' WHERE CODE = 'ES413';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES0704' WHERE CODE = 'ES414';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES0705' WHERE CODE = 'ES415';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES0706' WHERE CODE = 'ES416';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES0707' WHERE CODE = 'ES417';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES0708' WHERE CODE = 'ES418';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES0709' WHERE CODE = 'ES419';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES0801' WHERE CODE = 'ES421';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES0802' WHERE CODE = 'ES422';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES0803' WHERE CODE = 'ES423';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES0804' WHERE CODE = 'ES424';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES0805' WHERE CODE = 'ES425';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES0901' WHERE CODE = 'ES511';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES0902' WHERE CODE = 'ES512';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES0903' WHERE CODE = 'ES513';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES0904' WHERE CODE = 'ES514';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES1001' WHERE CODE = 'ES521';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES1002' WHERE CODE = 'ES522';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES1003' WHERE CODE = 'ES523';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES1101' WHERE CODE = 'ES431';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES1102' WHERE CODE = 'ES432';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES1201' WHERE CODE = 'ES111';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES1202' WHERE CODE = 'ES112';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES1203' WHERE CODE = 'ES113';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES1204' WHERE CODE = 'ES114';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES1601' WHERE CODE = 'ES211';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES1602' WHERE CODE = 'ES212';
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = 'ES1603' WHERE CODE = 'ES213';

-- Covering new codes inserted by istac:
UPDATE TB_LIS_GEOGR_VALUES SET GLOBAL_ORDER = UUID WHERE GLOBAL_ORDER is null;

-- Disable null
ALTER TABLE TB_LIS_GEOGR_VALUES MODIFY GLOBAL_ORDER VARCHAR2(255) NOT NULL;


-- drop order_in_granularity constraint AND COLUMN
ALTER TABLE TB_LIS_GEOGR_VALUES DROP CONSTRAINT GEOGR_VALUES_ORDER;
ALTER TABLE TB_LIS_GEOGR_VALUES DROP COLUMN ORDER_IN_GRANULARITY;

-- Add constraint
ALTER TABLE TB_LIS_GEOGR_VALUES ADD CONSTRAINT GEOGR_VALUES_ORDER UNIQUE(GLOBAL_ORDER);
