    	
DROP TABLE TB_INDIC_VERSIONS_LAST_VALUE CASCADE CONSTRAINTS PURGE;

    	
DROP TABLE TB_INDIC_INSTANCES_LAST_VALUE CASCADE CONSTRAINTS PURGE;

DROP SEQUENCE SEQ_INDIC_VERSIONS_LAST_VALUE;

DROP SEQUENCE SEQ_INDIC_INSTANCES_LAST_VALUE;


CREATE TABLE TB_INDIC_INST_LAST_VALUE (
  ID NUMBER(19) NOT NULL,
  LAST_TIME_VALUE VARCHAR2(255) NOT NULL,
  GEOGRAPHICAL_VALUE_FK NUMBER(19) NOT NULL,
  INDICATOR_INSTANCE_FK NUMBER(19) NOT NULL,
  LAST_DATA_UPDATED_TZ VARCHAR2(50) NOT NULL,
  LAST_DATA_UPDATED TIMESTAMP NOT NULL
);


    	
CREATE TABLE TB_INDIC_VERSION_LAST_VALUE (
  ID NUMBER(19) NOT NULL,
  LAST_TIME_VALUE VARCHAR2(255) NOT NULL,
  GEOGRAPHICAL_VALUE_FK NUMBER(19) NOT NULL,
  INDICATOR_VERSION_FK NUMBER(19) NOT NULL,
  LAST_DATA_UPDATED_TZ VARCHAR2(50) NOT NULL,
  LAST_DATA_UPDATED TIMESTAMP NOT NULL
);

ALTER TABLE TB_INDIC_INST_LAST_VALUE ADD CONSTRAINT PK_TB_INDIC_INST_LAST_VALUE
	PRIMARY KEY (ID)
;

		
ALTER TABLE TB_INDIC_VERSION_LAST_VALUE ADD CONSTRAINT PK_TB_INDIC_VERSION_LAST_VALUE
	PRIMARY KEY (ID)
;

ALTER TABLE TB_INDIC_INST_LAST_VALUE
	ADD CONSTRAINT UQ_TB_INDIC_INST_LAST_VALUE UNIQUE (GEOGRAPHICAL_VALUE_FK, INDICATOR_INSTANCE_FK)
;



ALTER TABLE TB_INDIC_VERSION_LAST_VALUE
	ADD CONSTRAINT UQ_TB_INDIC_VERSION_LAST_VALUE UNIQUE (GEOGRAPHICAL_VALUE_FK, INDICATOR_VERSION_FK)
;


ALTER TABLE TB_INDIC_INST_LAST_VALUE ADD CONSTRAINT FK_TB_INDIC_INST_LAST_VALUE_43
	FOREIGN KEY (GEOGRAPHICAL_VALUE_FK) REFERENCES TB_LIS_GEOGR_VALUES (ID)
;
ALTER TABLE TB_INDIC_INST_LAST_VALUE ADD CONSTRAINT FK_TB_INDIC_INST_LAST_VALUE_86
	FOREIGN KEY (INDICATOR_INSTANCE_FK) REFERENCES TB_INDICATORS_INSTANCES (ID)
;

  
ALTER TABLE TB_INDIC_VERSION_LAST_VALUE ADD CONSTRAINT FK_TB_INDIC_VERSION_LAST_VAL07
	FOREIGN KEY (GEOGRAPHICAL_VALUE_FK) REFERENCES TB_LIS_GEOGR_VALUES (ID)
;
ALTER TABLE TB_INDIC_VERSION_LAST_VALUE ADD CONSTRAINT FK_TB_INDIC_VERSION_LAST_VAL93
	FOREIGN KEY (INDICATOR_VERSION_FK) REFERENCES TB_INDICATORS_VERSIONS (ID)
;

CREATE SEQUENCE SEQ_INDIC_VERSION_LAST_VALUE;
CREATE SEQUENCE SEQ_INDIC_INST_LAST_VALUE;

  