ALTER TABLE TB_INDICATORS_INSTANCES
DROP COLUMN GEOGRAPHICAL_VALUE_FK;

ALTER TABLE TB_INDICATORS_INSTANCES
DROP COLUMN TIME_VALUE;

ALTER TABLE TB_INDICATORS_INSTANCES
ADD TIME_VALUES CLOB;

CREATE TABLE TB_INDIC_INST_GEO_VALUES (
  GEOGRAPHICAL_VALUE NUMBER(19) NOT NULL,
  TB_INDICATORS_INSTANCES NUMBER(19) NOT NULL
);


ALTER TABLE TB_INDIC_INST_GEO_VALUES ADD CONSTRAINT FK_TB_INDIC_INST_GEO_VALUES_53
	FOREIGN KEY (GEOGRAPHICAL_VALUE) REFERENCES TB_LIS_GEOGR_VALUES (ID)
;
ALTER TABLE TB_INDIC_INST_GEO_VALUES ADD CONSTRAINT FK_TB_INDIC_INST_GEO_VALUES_91
	FOREIGN KEY (TB_INDICATORS_INSTANCES) REFERENCES TB_INDICATORS_INSTANCES (ID)
;