CREATE TABLE TB_INDICATORS_SYSTEMS_HIST (
  ID NUMBER(19) NOT NULL,
  VERSION_NUMBER VARCHAR2(255) NOT NULL,
  PUBLICATION_DATE_TZ VARCHAR2(50) NOT NULL,
  PUBLICATION_DATE TIMESTAMP NOT NULL,
  INDICATORS_SYSTEM_FK NUMBER(19) NOT NULL
);

ALTER TABLE TB_INDICATORS_SYSTEMS_HIST ADD CONSTRAINT PK_TB_INDICATORS_SYSTEMS_HIST
	Primary Key (Id)
;

ALTER TABLE TB_INDICATORS_SYSTEMS_HIST
	Add Constraint Uq_Tb_Indicators_Systems_Hist Unique (Version_Number, Indicators_System_Fk)
;

ALTER TABLE TB_INDICATORS_SYSTEMS_HIST ADD CONSTRAINT FK_TB_INDICATORS_SYSTEMS_HIS62
	Foreign Key (Indicators_System_Fk) References Tb_Indicators_Systems (Id)
;

CREATE SEQUENCE SEQ_INDICATORS_SYSTEMS_HIST;