(function () {
    "use strict";

    App.constants.WidgetConstants = {
        MIN_WIDTH_SLIDER_PERCENTAGE_VALUE: 10,
        MAX_WIDTH_SLIDER_PERCENTAGE_VALUE: 100,
        MIN_WIDTH_SLIDER_PIXEL_VALUE: 100,
        MAX_WIDTH_SLIDER_PIXEL_VALUE: 700,
        DEFAULT_PERCENTAGE_WIDTH: 100,
        DEFAULT_PIXEL_WIDTH: 423,
        MIN_HEIGHT_SLIDER_PERCENTAGE_VALUE: 30,
        MAX_HEIGHT_SLIDER_PERCENTAGE_VALUE: 100,
        MIN_HEIGHT_SLIDER_PIXEL_VALUE: 150,
        MAX_HEIGHT_SLIDER_PIXEL_VALUE: 700,
        DEFAULT_PERCENTAGE_HEIGHT: 100,
        DEFAULT_PIXEL_HEIGHT: 423
    };
}());
